// Game-facing vocabulary. Internal keys appear only as supplementary identifiers.
export const labels={
 id:'識別子',name:'名前',title:'表示名',description:'説明',text:'本文',brief:'依頼の概要',past:'依頼前の出来事',progression:'進行の説明',role:'役割',limitation:'制約',note:'調査時の説明',version:'内容版',schemaVersion:'形式の版',source:'出典',examples:'参考資料',profile:'共通設定',region:'地域',recommendedLevel:'推奨レベル',floor:'階層',dungeon:'所属迷宮',map:'配置マップ',maps:'所属マップ',x:'横位置',y:'縦位置',z:'高さ',edge:'設置する面',facing:'向き',direction:'向き',entrance:'入口',entries:'入口',main:'通常入口',point:'入口の位置',points:'配置地点',at:'出発地点',destination:'移動先',a:'接続口A',b:'接続口B',links:'接続',objects:'配置物',kind:'種類',trigger:'起動方法',triggers:'通知の種類',script:'実行する処理',scripts:'処理',commands:'処理の順序',condition:'実行条件',visibleWhen:'出現条件',requirement:'実行できない場合の説明',once:'一回限り',blocking:'通路を塞ぐ',safe:'安全な地点',initialState:'初期状態',state:'状態',fire:'灯火',effect:'効果',effects:'効果',radius:'効果範囲',litStates:'点灯している状態',watch:'監視する変化',repeat:'再発方法',action:'成立時の処理',message:'通知文',fieldEvents:'条件付きイベント',systems:'仕掛け',use:'仕掛けの種類',enabled:'有効',
 hp:'HP',mp:'MP',str:'力',vit:'防御',agi:'速さ',int:'知力',stats:'能力値',growth:'成長値',level:'習得レベル',skills:'戦闘技能',skill:'戦闘技能',abilities:'探索特技',ability:'探索特技',fieldAbilities:'探索特技',grants:'習得する技能・特技',equipment:'装備できる種類',weapon:'武器',armor:'防具',charm:'装飾品',equipmentTypes:'装備の分類',equipmentPatches:'既存装備の調整',passives:'常時効果',physicalPower:'物理威力倍率',magicPower:'魔法威力倍率',healingPower:'回復倍率',itemHealing:'道具回復倍率',damageTaken:'被害倍率',encounterRate:'遭遇率',escapeBonus:'逃走率補正',shopDiscount:'購入割引率',retreatCost:'帰還費用倍率',revealRadius:'地図記録範囲',trapDamage:'罠の被害倍率',lightSaveEvery:'燃料を節約する歩数',elementPower:'属性威力倍率',initialJobs:'仲間の初期職業',commonSkills:'共通技能',legacyGrowth:'旧形式の成長値',statNames:'能力値の表示名',jobs:'職業',job:'職業',buffs:'一時強化・弱体',buff:'強化・弱体',turns:'持続ターン',resist:'属性耐性',statuses:'状態異常',status:'状態異常',stepDamage:'歩行時ダメージ',turnDamage:'ターン終了時ダメージ',target:'対象',api:'処理の種類',maxTargets:'対象人数の上限',lifetime:'有効な期間',modes:'使える場面',materials:'消費する道具',output:'作成する道具',items:'道具',item:'道具',count:'個数',price:'価格',shopGoods:'店の追加商品',formulas:'計算式',formula:'計算式',skillCues:'技能の演出',cue:'演出',type:'種類',slot:'装備部位',power:'威力',amount:'増減量',ratio:'割合',cost:'費用',gold:'所持金',xp:'経験値',actors:'仲間',actor:'仲間',monsters:'魔物',enemies:'敵',enemy:'敵',sprite:'表示画像',portrait:'肖像',encounters:'遭遇編成',encounter:'遭遇編成',escape:'逃走できる',loot:'入手品',drops:'落とす道具',weight:'抽選の重み',chance:'確率',element:'属性',scale:'倍率',heal:'回復量',
 parent:'上位の場所',background:'背景画像',cast:'登場人物',character:'人物',shop:'店を利用できる',party:'隊の編成ができる',quests:'依頼を扱う',services:'利用できるサービス',dungeons:'迷宮への出入口',display:'人物の表示',position:'表示位置',flip:'左右反転',layer:'重なり順',asset:'素材',speaker:'話者の表記',
 presets:'セル種',legend:'セル記号と種類',rows:'セル配置',overrides:'地点ごとの上書き',visual:'外観と遮光',passable:'通行できる',wall:'壁を描く',floorVisible:'床を描く',opaque:'光を遮る',material:'素材の種類',image:'表示画像',parameters:'セルの性質',illumination:'局所照度',water_passable:'水を通す',events:'イベント',tile:'通行状態',tiles:'通行配置',layers:'変更後のセル',openedLayers:'開いた後のセル',closedLayers:'閉じた後のセル',initiallyKnown:'最初から分かる場所',mapOpenings:'旧形式の開口地点',mapKnown:'旧形式の既知の場所',retiredMaps:'通常配信しないマップ',retiredScriptFiles:'通常配信しない処理',
 entryFixture:'入口の火台',fuelItem:'燃料の道具',emberItem:'種火の道具',portable:'携帯松明',capacity:'容量',baseEffect:'通常の火',entryEffect:'入場時の火',warnings:'燃料の警告位置',threat:'無防護時の遭遇',encounterPool:'遭遇する敵の抽選',repels:'くらがりを防ぐ',enemyScale:'敵の能力倍率',priority:'優先順位',fixtures:'火台・松明の配置',initiallyLit:'最初から点灯',phases:'水位の段階',duration:'継続時間',controls:'操作盤',initiallyOpen:'最初から開く',floors:'対象区画',protectionItem:'防護する道具',min:'最小値',max:'最大値',perBattle:'一戦ごとの変化',eater:'腐食を起こす敵',threshold:'発動する境界値',washZones:'洗い場',walls:'破壊できる壁',species:'植物の種類',plots:'植える場所',terrain:'生み出す地形',harvest:'収穫物',immatureHarvest:'未成熟時の収穫物',bridge:'橋',barrier:'障壁',vine:'つた',supply:'補給地点',supplies:'補給品',portals:'転移口',mode:'動作方式',initial:'初期設定',interval:'切替間隔',states:'切替後の地形',refuges:'退避場所',perStep:'一歩ごとの変化',maxStacks:'蓄積上限',factor:'補正倍率',vectors:'帰路の向き',vectorRows:'帰路の矢印配置',dx:'横方向',dy:'縦方向',cells:'対象セル',blockedSkills:'使用を禁止する技能',blockedAbilities:'使用を禁止する特技',suppressedSkills:'効果を抑制する技能',books:'書物',gates:'扉',warning:'警告位置',perRound:'一ターンごとの変化',suffocation:'窒息時ダメージ',water:'水没設定',pockets:'空気のある場所',devices:'装置',closeAt:'閉鎖する警戒値',maxAlarm:'警戒値の上限',escortSteps:'護衛の継続歩数',escortRate:'護衛中の遭遇倍率',escortEnemyScale:'護衛中の敵倍率',guardEncounter:'守護者の遭遇編成',offers:'取引',guards:'護衛',repairsPerRun:'入場ごとの修理回数',zones:'水密区画',initiallyFlooded:'最初から水没',initiallyPowered:'最初から動く',powerCost:'動力消費',charge:'動力回復',requirements:'必要な条件',rewards:'得られるもの',
 sounds:'効果音',sound:'効果音',instrument:'音色',gain:'音量',notes:'音符',pitch:'音の高さ',start:'開始時間',seconds:'長さ',velocity:'音の強さ',category:'分類',tracks:'効果の構成',frames:'動きの変化点',columns:'画像の横コマ数',cell:'一コマの大きさ',palette:'基本色',gap:'再生間隔',impact:'命中までの時間（ms）',anticipation:'敵の予備動作',directed:'攻撃元から押し戻す',pattern:'攻撃の形',bindings:'行動と演出の対応',actions:'プレイヤーの操作',ambient:'常時表示',darkness:'暗さ',color:'色',opacity:'濃さ',maxOpacity:'最大の濃さ',shade:'周辺の陰影',axis:'切断方向',distance:'移動距離',rotate:'回転角',offset:'再生位置',translateX:'横移動',translateY:'縦移動',scaleX:'横倍率',scaleY:'縦倍率',skewX:'横傾斜',skewY:'縦傾斜',volume:'音量',delay:'開始の遅延',
 outcomes:'結末',outcome:'結末',label:'表示名',nodes:'場面',options:'選択肢',to:'次の場面',then:'条件を満たすとき',else:'満たさないとき',cases:'値ごとの分岐',equals:'一致する値',default:'それ以外',branches:'抽選する分岐',args:'引数',value:'値',key:'フラグ',on_win:'勝利後',on_lose:'敗北後',on_escape:'逃走後',on_interrupt:'中断後',quest:'クエスト',scene:'場面',storyAction:'物語上の行為',storyQuest:'所属クエスト',dungeonScene:'迷宮の調査処理',fuel:'残り燃料',event:'イベント',ref:'調べる値',left:'調べる対象',right:'比較する値',arg:'対象の条件',metric:'戦績の種類',sinceQuest:'この依頼の受注後',format:'文章の書式',values:'差し込む値',
 tileset:'素材集',atlas:'素材画像',rect:'切り出し範囲',width:'幅',height:'高さ',variants:'見た目の種類',wallAtlas:'壁の素材画像',deviceAtlas:'装置の素材画像',fallback:'標準の素材',regions:'地域別素材',
};
export const commandNames={
 'scene.cast':'人物を配置する','scene.cast.clear':'人物の表示を戻す','fire.portable.set':'携帯松明を設定する','story.init':'物語を開始する','story.scene':'物語の場面を進める','story.action':'物語上の行為を実行する','story.journey':'目的地への移動を始める',say:'台詞を表示する',narrate:'地の文を表示する',choice:'選択肢を出す',if:'条件で分岐する',switch:'値によって分岐する',call:'別の処理を呼ぶ',return:'呼び出し元へ戻る',jump:'別の処理へ移る',set:'値を設定する',add:'値を増減する','flag.set':'フラグを設定する','random.set':'乱数を設定する','random.branch':'確率で分岐する','item.give':'道具を渡す','item.take':'道具を消費する','gold.change':'所持金を増減する','actor.heal':'HPを回復する','actor.damage':'HPを減らす','actor.restore_mp':'MPを回復する','party.heal_all':'隊全体を回復する','party.join':'仲間を加える','party.leave':'仲間を外す','status.apply':'状態異常を付ける','status.remove':'状態異常を治す','map.teleport':'指定地点へ移動する','map.reveal':'周囲の地図を記録する','facing.set':'向きを変える','object.state.set':'配置物の状態を変える','event.mark_done':'イベントを完了にする','battle.end':'イベント戦闘を終える','battle.start':'戦闘を開始する','quest.accept':'依頼を受注する','quest.evidence':'証拠を記録する','quest.complete':'依頼を完了する','scene.background':'背景を変える','audio.bgm':'BGMを再生する','audio.se':'効果音を再生する','effect.play':'効果を再生する','screen.set':'画面に色を重ねる','screen.clear':'画面の色を戻す',rest:'休息する','town.return':'町へ戻る','light.refill':'灯油を補充する','ending.set':'結末を表示する','job.change':'職業を変える','job.action':'探索特技を実行する'};
export const expressionNames={eq:'等しい',ne:'等しくない',gt:'より大きい',gte:'以上',lt:'より小さい',lte:'以下',in:'候補に含まれる',contains:'含む',and:'すべて満たす',or:'いずれかを満たす',not:'満たさない',exists:'値がある',has_item:'道具を持っている',has_member:'仲間が同行している',has_status:'状態異常がある',event_done:'イベントが完了している',map_discovered:'地点を発見している',object_state:'配置物の状態',record_count:'戦績の回数',add:'合計',sub:'差',mul:'積',div:'割り算',mod:'余り',min:'最小',max:'最大',floor:'切り捨て',ceil:'切り上げ',round:'四捨五入',abs:'絶対値',clamp:'範囲内に収める'};
export const systemNames={fire_network:'篝火・携帯松明',waterworks:'水位と水門',corrosion:'腐食と洗浄',breakable_walls:'破壊できる壁',plant_garden:'植物と地形',warp_network:'鏡の転移',terrain_shift:'地形の切替',vector_curse:'帰路の呪い',suppression_zone:'効果を遮る境界',skill_library:'書物と技能の封印',air_supply:'空気供給',market_pacts:'取引と護衛',power_grid:'動力と装置',map_connections:'マップ間の接続',compartment_water:'水密区画と排水',voxel_space:'旧3D地形（互換原稿）'};
export const enumNames={north:'北',east:'東',south:'南',west:'西',enter:'セルへ入ったとき',interact:'調べたとき',action:'操作したとき',once:'一回限り',entry:'入場ごと',change:'変化ごと',battle:'戦闘',script:'処理',decision:'会話・判断',clue:'調査',stairs:'階段',door:'扉',chest:'宝箱',fountain:'泉',trap:'罠',exit:'出口',enemy:'敵一体',all_enemies:'敵全体',ally:'味方一人',all_allies:'味方全体',self:'自分',party:'隊全体',scene:'場面全体',screen:'画面全体',target:'選んだ対象',town:'町',dungeon:'迷宮',location:'現在地',active:'進行中',available:'受注可能',locked:'未開放',completed:'完了',failed:'失敗',manual:'操作で切替',random:'自動抽選',gate:'水門',valve:'弁',left:'左',center:'中央',right:'右',stage:'立ち絵',cards:'人物カード',fire:'炎',ice:'氷',lightning:'雷',light:'光',dark:'闇',physical:'物理',weapon:'武器',armor:'防具',charm:'装飾品',heavy:'重装',cloth:'布装備',sword:'剣',axe:'斧',spear:'槍',bow:'弓',knife:'短剣',staff:'杖',mace:'棍棒',fist:'拳',book:'書物',strike:'物理攻撃の軌跡',slash:'斬撃',blunt:'打撃',pierce:'刺突',motion:'移動・変形',split:'切断',sprite:'コマ画像',tint:'色を重ねる',shade:'周辺を暗くする',animation:'画像アニメーション',field:'フィールド効果',vertical:'縦',diagonal:'斜め',battles:'戦闘回数',wins:'勝利回数',escapes:'逃走回数',losses:'敗北回数',repels:'撃退回数',interruptions:'中断回数',kills:'討伐数',encounters:'遭遇数',inn:'宿泊',recruit:'仲間の募集',clinic:'治療',kick:'低い打撃',snare:'雑音の打撃',hat:'高い打撃',bass:'低音',pluck:'弾く音',bell:'鐘',pad:'持続音',pulse:'矩形波',flute:'笛',ordinary:'通常の火',ward:'くらがり除けの火',calm:'鎮めの火',lure:'呼び寄せの火',deep:'深火',floor:'床',wall:'壁','.':'通行可能','#':'通行不可'};
export const units={x:'セル',y:'セル',z:'段',radius:'セル',illumination:'0〜8',price:'G',gold:'G',cost:'G',mp:'MP',hp:'HP',count:'個',level:'レベル',seconds:'秒',start:'秒',delay:'ms',gap:'ms',duration:'ms',pitch:'MIDI音高',velocity:'0〜127',opacity:'0〜1',gain:'0〜1',turns:'ターン',capacity:'歩分',perStep:'一歩ごと'};
export const help={repels:'くらがりを防ぎます。通常の魔物の抑制は遭遇率で指定します。',encounterRate:'threatでは歩行抽選の確率（0〜1）、灯火などの効果では通常遭遇率への倍率です。0は遭遇を抑制します。',condition:'この条件が成立した場合に実行します。',visibleWhen:'この条件が成立した場合に対象を表示します。',edge:'設置セルで、この面を向いて調べたときに操作できます。',blocking:'この配置物があるセルを通行できなくします。',once:'完了したイベントを再び実行しません。',openedLayers:'通行の変化に合わせ、表示・遮光・通水なども指定します。',target:'誰・どこへ作用させるかを指定します。'};
Object.assign(labels,{literal:'値',passage:'通行',object:'配置物',assets:'素材画像',device:'装置素材',art:'素材',alarm:'警戒値',circuit:'回路',salvage:'回収物',side:'設置面',control:'操作盤',voxels:'旧3Dの層・面・経路',music:'BGM',minZ:'最下層の高さ',faces:'面の設定',initialWater:'初期の水',operable:'操作できる',closed:'閉じたとき',open:'開いたとき',handle:'取っ手',support:'足場',path:'経路',bidirectional:'往復できる',access:'通行方法',when:'成立条件',requires:'必要条件',location:'場所',from:'出発点',to:'移動先',detail:'説明',consumed:'使用すると消費する',battleSkill:'戦闘で使う技能',equipmentType:'装備の分類',requiresWeapon:'必要な武器の種類',requiresAnalyzed:'分析が必要',selfEffects:'使用者への効果',fireEffect:'灯火への効果',authoringNotes:'制作上の制約',facts:'維持する事実',factsHeading:'事実の見出し',notice:'注意書き',ideas:'演出の案',ai:'行動の優先順位',statusImmune:'無効にする状態異常',formulaValue:'計算式',field:'探索中に使える',monster:'魔物',actor:'仲間',system:'仕掛け',stock:'商品',story:'物語'});
Object.assign(enumNames,{...commandNames,...expressionNames,...systemNames,earth:'土',damage:'ダメージ',heal:'HP回復',restore_mp:'MP回復',drain_mp:'MP吸収',guard:'防御',status:'状態異常',cleanse:'状態異常を治す',buff:'強化・弱体',cover:'かばう',analyze:'分析',repel:'撃退',consumable:'消耗品',material:'素材',equipment:'装備',key:'重要品',dungeon_tool:'迷宮の道具',entrance:'入口',watertight_door:'水密扉',battle:'戦闘',start:'開始時',round_start:'ターン開始時',before_end:'終了前',move:'移動時',object:'配置物の変化',state:'状態の変化',classic:'通常探索',bridge:'橋',barrier:'障壁',vine:'つた',str:'力',vit:'防御',agi:'速さ',int:'知力','battle.skill':'戦闘技能','archive.unlock':'書物の封印を解く','inventory.convert':'道具を加工する','fire.kindling':'火を起こす','wall.break':'壁を壊す','party.heal':'隊を回復する','voxel.traverse':'旧3Dの経路を渡る','water.traverse':'水中を渡る','party.dry':'濡れを解消する',toll:'通行料',barter:'物々交換',buy:'購入',escort:'護衛',guardian:'守護者',elevator:'昇降機',repair:'修理',equipped:'装備中',up:'上',down:'下',ladder:'はしご',rope:'縄',fixed:'固定',install:'設置',skill:'技能',pump:'排水',dig:'掘削',auto:'自動'});
export const label=key=>labels[key]??key;
export const enumLabel=value=>value===null?'なし':enumNames[value]??String(value);

Object.assign(labels,{surface:'表面の模様',water_depth:'固定水深（0〜2）',slippery:'進入方向へ滑る',fragile:'離れた後に崩れる',safe:'通常の歩行遭遇を抑止',binding:'連動する仕掛け',corrosion:'一歩の塩蓄積'});
Object.assign(enumNames,{stone:'通常の石',earth:'土',wood:'木目',wet:'濡れた石',cracked:'亀裂',salt:'塩',roots:'根',thorns:'茨',poison:'毒沼',corrosion:'腐食',rune:'紋様',rock:'岩盤',air_pocket:'空気溜まり',root_bridge:'根橋の対象',thorn_wall:'茨の対象'});

Object.assign(enumNames,{poison_step:'毒沼への進入'});

Object.assign(labels,{floor_depth:'くぼみの深さ（m）',bottomless:'底が見えない',water_level:'水面の高さ（m・周囲の床が0）'});
