import {voxelSchema,voxelSystemSchema} from './voxel-schema.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {COMMANDS} from '../src/core/script.js';
import {additionalDungeonSystems} from './dungeon-system-schemas.mjs';
const folder=path.resolve(import.meta.dirname,'../data/schemas');await fs.mkdir(folder,{recursive:true});
const string={type:'string',minLength:1},integer={type:'integer',minimum:0},boolean={type:'boolean'},value={$ref:'#/$defs/value'},expr={$ref:'#/$defs/expression'},commands={type:'array',items:{$ref:'#/$defs/command'}};
const obj=(properties,required=Object.keys(properties),additionalProperties=false)=>({type:'object',properties,required,additionalProperties});
const variants=[];
const command=(names,properties={},required=Object.keys(properties))=>{for(const name of names.split(' '))variants.push(obj({op:{const:name},...properties},['op',...required]));};
command('fire.portable.set',{fuel:integer,effect:{type:['string','null']}});
command('story.init',{quest:string});command('story.scene',{quest:string,scene:string});command('story.action',{quest:string,action:string});
command('say narrate',{text:value,name:{type:'string'},speaker:{type:'string'}},['text']);
command('choice',{options:{type:'array',minItems:1,items:obj({id:string,text:string,condition:value,visibleWhen:value,requirement:{type:'string'},storyAction:obj({quest:string,action:string}),commands},['id','text','commands'])}});
command('if',{condition:value,then:commands,else:commands});
command('switch',{value,cases:{type:'array',items:obj({equals:value,commands})},default:commands});
command('call',{script:string,args:{type:'object',additionalProperties:value}},['script']);command('return');command('jump',{script:string});
command('set add',{target:string,value});command('flag.set',{key:string,value});command('random.set',{target:string,min:{type:'integer'},max:{type:'integer'}});
command('random.branch',{branches:{type:'array',minItems:1,items:obj({weight:{type:'number',exclusiveMinimum:0},commands})}});
command('item.give item.take',{item:value,count:{oneOf:[{type:'integer',minimum:1},expr]}},['item']);command('gold.change',{amount:value});
command('actor.heal actor.damage actor.restore_mp',{target:value,amount:value});command('party.heal_all',{ratio:{type:'number',minimum:0,maximum:1}},[]);
command('party.join party.leave',{actor:string});command('status.apply status.remove',{target:value,status:string});
command('map.teleport',{map:string,x:integer,y:integer,z:{type:'integer'},facing:{enum:['north','east','south','west']}},['map','x','y']);command('map.reveal',{radius:integer},[]);command('facing.set',{direction:{enum:['north','east','south','west']}});
command('object.state.set',{map:string,object:string,state:string},['map','object','state']);command('event.mark_done',{event:string});
command('battle.start',{encounter:string,on_win:commands,on_lose:commands,on_escape:commands});command('quest.accept',{quest:string});command('quest.evidence',{quest:string,key:string,text:string});command('quest.complete',{quest:string,outcome:string});
command('scene.background audio.bgm',{asset:string});command('audio.se',{asset:string,volume:{type:'number',minimum:0,maximum:1},delay:{type:'number',minimum:0,maximum:5000}},['asset']);command('effect.play',{effect:string,target:{type:'string',pattern:'^(scene|screen|party|actor:[a-z][a-z0-9_]*|enemy:enemy_[0-7])$'},delay:{type:'number',minimum:0,maximum:5000}},['effect']);command('screen.set',{layer:{type:'string',pattern:'^[a-z][a-z0-9_]{0,31}$'},color:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},opacity:{type:'number',minimum:0,maximum:.65},shade:boolean},['layer','color','opacity']);command('screen.clear',{layer:string});command('rest',{cost:integer,ratio:{type:'number',minimum:0,maximum:1}},[]);command('town.return light.refill');command('ending.set',{title:string,text:string});
command('job.change',{actor:string,job:string});command('job.action',{actor:string,ability:string});
if(variants.length!==COMMANDS.size)throw Error('Schema/command registry mismatch');
const expressionVariants=[obj({ref:string}),obj({format:{type:'string'},values:{type:'object',additionalProperties:value}})];
for(const op of ['eq','ne','gt','gte','lt','lte','in','contains'])expressionVariants.push(obj({op:{const:op},left:value,right:value}));
for(const op of ['and','or','add','sub','mul','div','mod','min','max','floor','ceil','round','abs','clamp'])expressionVariants.push(obj({op:{const:op},args:{type:'array',minItems:1,items:value}}));
expressionVariants.push(obj({op:{const:'not'},arg:value}),obj({op:{const:'exists'},value}),obj({op:{const:'has_item'},item:string,count:{type:'integer',minimum:1}},['op','item']),obj({op:{const:'has_member'},actor:string}),obj({op:{const:'has_status'},actor:string,status:string}),obj({op:{const:'event_done'},event:string}),obj({op:{const:'map_discovered'},map:string,x:integer,y:integer,z:{type:'integer'}},['op','map','x','y']));
expressionVariants.push(obj({op:{const:'object_state'},map:string,object:string,default:string},['op','map','object']));
expressionVariants.push(obj({op:{const:'record_count'},metric:{enum:['battles','wins','escapes','losses','repels','kills','encounters']},id:string,sinceQuest:string},['op','metric']));
const definitions={value:{oneOf:[{type:['string','number','boolean','null']},{type:'array',items:value},expr]},expression:{oneOf:expressionVariants},command:{oneOf:variants},script:obj({commands,storyQuest:string,dungeonScene:string},['commands'])};
const base={"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":definitions};
const write=(name,content)=>fs.writeFile(path.join(folder,name),JSON.stringify({...base,...content},null,2)+'\n');
await write('script.schema.json',{title:'灯帰り DSL v1 スクリプト',...obj({scripts:{type:'object',additionalProperties:{$ref:'#/$defs/script'}}})});
const storyStrings={type:'array',uniqueItems:true,items:string};
const effectVariant=(op,props,required=Object.keys(props))=>obj({op:{const:op},...props,when:value},['op',...required]);
const storyEffect={oneOf:[
 effectVariant('move',{entities:{...storyStrings,minItems:1},path:{type:'array',minItems:2,items:string},assistant:string,carrier:string},['entities','path']),
 effectVariant('transfer',{entity:string,from:string,to:string}),effectVariant('set',{key:string,value}),
 effectVariant('pour',{from:string,to:string,amount:{type:'integer',minimum:1}}),effectVariant('consume',{key:string,amount:{type:'integer',minimum:1},sink:string}),
 effectVariant('observe',{observer:string,proposition:string,source:string,requires:value})
]};
const registryField={oneOf:[obj({type:{const:'boolean'},initial:boolean,meaning:string}),obj({type:{const:'enum'},initial:string,values:{...storyStrings,minItems:1},meaning:string}),obj({type:{const:'integer'},initial:{type:'integer'},min:{type:'integer'},max:{type:'integer'},meaning:string,container:string},['type','initial','min','max','meaning'])]};
const storySchema=obj({version:{const:1},modelVersion:{const:'1.1'},places:{type:'object',minProperties:1,additionalProperties:string},connections:{type:'array',items:{type:'array',minItems:2,maxItems:2,items:string}},registry:{type:'object',minProperties:1,additionalProperties:registryField},entities:{type:'object',additionalProperties:obj({holder:string,kind:{enum:['person','group','item']},character:string,mobility:string},['holder','kind'])},propositions:{type:'object',additionalProperties:obj({text:string})},initialKnowledge:{type:'object',additionalProperties:storyStrings},invariants:{type:'array',items:obj({id:string,condition:value,message:string})},scenes:{type:'object',additionalProperties:obj({title:string,place:string,requires:value,cast:{type:'array',items:obj({entity:string,when:value,mode:{enum:['local','remote']},requires:value},['entity'])}})},actions:{type:'object',additionalProperties:obj({from:{...storyStrings,minItems:1},to:string,ending:string,requires:value,effects:{type:'array',items:storyEffect},once:boolean,cost:{type:'object',additionalProperties:{type:'integer',minimum:1}}},['from','requires','effects'])},endings:{type:'object',additionalProperties:value}});
storySchema.properties.revision={type:'integer',minimum:1};
const questEvent=obj({fire:obj({effect:string,radius:{type:'integer',minimum:0,maximum:30},litStates:{type:'array',minItems:1,uniqueItems:true,items:string}}),id:string,title:string,dungeon:string,points:{type:'array',minItems:1,items:obj({map:string,x:integer,y:integer,z:{type:'integer'}},['map','x','y'])},kind:{enum:['exit','stairs','chest','fountain','trap','door','clue','decision']},trigger:{enum:['enter','interact','action']},script:string,role:string,safe:boolean,once:boolean,blocking:boolean,initialState:string,visibleWhen:value,condition:value,requirement:string,note:obj({text:string,when:value})},['id','title','points','trigger','script']);
await write('quest-events.schema.json',{title:'クエスト固有イベント原稿',...obj({events:{type:'array',items:questEvent},scripts:{type:'object',additionalProperties:{$ref:'#/$defs/script'}}})});
await write('quest.schema.json',{title:'灯帰り DSL v1 クエスト',...obj({schemaVersion:{const:1},id:string,number:{type:'integer',minimum:1},title:string,client:string,brief:string,region:{type:'integer',minimum:1},type:string,recommendedLevel:{type:'integer',minimum:1},requires:value,unlockHint:{type:'string'},events:{type:'array',items:questEvent},locations:{type:'array',minItems:1,items:obj({map:string,object:string,x:integer,y:integer,z:{type:'integer'},role:string},['map','object','x','y','role'])},outcomes:{type:'object',minProperties:2,additionalProperties:obj({label:string,text:string,gold:integer,xp:integer,requires:value},['label','text','gold','xp'])},story:storySchema,legacyOutcomes:{type:'object'},model:{type:'object',required:['world','agents','conflict','narrative','audience','reveal','beats']},scripts:{type:'object',additionalProperties:{$ref:'#/$defs/script'}}},['schemaVersion','id','number','title','client','brief','region','type','recommendedLevel','requires','unlockHint','events','locations','outcomes','model','scripts'])});
await write('map.schema.json',{title:'灯帰り DSL v1 グリッドマップ',...obj({id:string,region:{type:'integer',minimum:1},floor:{type:'integer',minimum:1},name:string,voxels:voxelSchema,tiles:{type:'array',minItems:3,items:{type:'string',pattern:'^[#.]+$'}},entrance:obj({x:integer,y:integer,z:{type:'integer'},facing:{enum:['north','east','south','west']}},['x','y','facing']),background:string,music:string,encounter:string,encounterPool:{type:'array',minItems:1,items:obj({encounter:string,weight:{type:'number',exclusiveMinimum:0}})},encounterRate:{type:'number',minimum:0,maximum:1},initiallyKnown:{type:'array',uniqueItems:true,items:{type:'string',pattern:'^\\d+,\\d+(,-?\\d+)?$'}},objects:{type:'array',items:obj({id:string,x:integer,y:integer,z:{type:'integer'},name:string,kind:{enum:['exit','stairs','chest','fountain','trap','door','clue','decision']},trigger:{enum:['enter','interact']},safe:boolean,once:boolean,blocking:boolean,initialState:string,visibleWhen:value,condition:value,script:string},['id','x','y','name','kind','trigger','script'])}},['id','region','floor','name','tiles','entrance','background','music','encounter','encounterRate','objects'])});
await write('game.schema.json',{title:'灯帰り DSL v1 作品マニフェスト',...obj({schemaVersion:{const:1},id:string,version:string,recordVersion:{const:1},storyVersion:{const:1},dungeonVersion:{const:1},title:string,subtitle:string,startScript:string,initial:obj({gold:integer,members:{type:'array',minItems:1,maxItems:5,uniqueItems:true,items:string},inventory:{type:'object',additionalProperties:integer}}),services:{type:'array',items:obj({id:string,label:string,detail:string,script:string})},tavern:obj({name:string,description:string,candidates:{type:'array',minItems:1,uniqueItems:true,items:string}}),migrations:{type:'object',additionalProperties:obj({actors:{type:'array',minItems:1,uniqueItems:true,items:string},scenarioRevision:boolean,dungeonRevision:boolean,environmentRevision:boolean,addedSystems:{type:'object',additionalProperties:{type:'array',items:string}},preserveRecords:boolean,legacyQuestRouting:boolean,quests:{type:'array',minItems:1,uniqueItems:true,items:string}},['actors'])},files:obj({databases:{type:'object',additionalProperties:string},maps:{type:'array',items:string},quests:{type:'array',items:string},scripts:{type:'array',items:string}})},['schemaVersion','id','version','title','subtitle','startScript','initial','services','files'])});
console.log(`Generated schemas for ${COMMANDS.size} commands, game, maps and quests`);
const numeric=(min,max)=>({type:'number',minimum:min,maximum:max}),color={type:'string',pattern:'^#[0-9a-fA-F]{6}$'};
const frame=obj({at:numeric(0,1),x:numeric(-200,200),y:numeric(-200,200),rotate:numeric(-360,360),skewX:numeric(-40,40),skewY:numeric(-40,40),scaleX:numeric(.1,3),scaleY:numeric(.1,3),opacity:numeric(0,1)},['at']);
const track={oneOf:[obj({kind:{const:'motion'},frames:{type:'array',minItems:2,maxItems:32,items:frame}}),obj({kind:{const:'sprite'},asset:string,frames:{type:'integer',minimum:2,maximum:64},columns:{type:'integer',minimum:1,maximum:64},cell:{type:'integer',minimum:8,maximum:512},scale:numeric(.1,3)},['kind','asset','frames','columns','cell']),obj({kind:{const:'split'},axis:{enum:['vertical','diagonal']},distance:numeric(0,100),rotate:numeric(-45,45)}),obj({kind:{enum:['tint','shade']},color,opacity:numeric(0,.65)})]};
await fs.writeFile(path.join(folder,'effects.schema.json'),JSON.stringify({$schema:base.$schema,title:'灯帰り 表示演出',type:'object',additionalProperties:obj({name:string,category:{enum:['script','animation','field']},duration:numeric(50,5000),tracks:{type:'array',minItems:1,maxItems:8,items:track},palette:color},['name','category','duration','tracks'])},null,2)+'\n');
await fs.writeFile(path.join(folder,'sounds.schema.json'),JSON.stringify({$schema:base.$schema,title:'灯帰り SE',type:'object',additionalProperties:obj({name:string,asset:string,gain:numeric(0,1)})},null,2)+'\n');

const jobStats=Object.fromEntries(['hp','mp','str','vit','agi','int'].map(k=>[k,numeric(0,100)]));
const strings={type:'array',uniqueItems:true,items:string};
const rates={type:'object',additionalProperties:numeric(0,3)};
const grants=obj({skill:string,level:{type:'integer',minimum:1,maximum:30},api:{enum:['battle.skill','map.reveal','inventory.convert','fire.kindling','wall.break','archive.unlock','party.heal','voxel.traverse','water.traverse','party.dry']},target:{enum:['self','ally','enemy','all_allies','all_enemies','location']},maxTargets:{type:'integer',minimum:1,maximum:8},lifetime:{const:'equipped'}});
const job=obj({id:string,name:string,role:string,limitation:string,growth:obj(jobStats),stats:obj(Object.fromEntries(Object.keys(jobStats).map(k=>[k,numeric(-100,100)])),[]),equipment:obj({weapon:strings,armor:strings,charm:strings}),passives:{type:'object',additionalProperties:{oneOf:[numeric(0,100),rates]}},grants:{type:'array',minItems:1,items:grants}});
await fs.writeFile(path.join(folder,'jobs.schema.json'),JSON.stringify({$schema:base.$schema,title:'灯帰り 職業定義 v1.3',type:'object',additionalProperties:job},null,2)+'\n');
const buff=obj({id:string,name:string,turns:{type:'integer',minimum:1,maximum:10},stats:obj(Object.fromEntries(['str','vit','agi','int'].map(k=>[k,numeric(.1,3)])),[]),resist:{type:'object',additionalProperties:numeric(0,1)}});
await fs.writeFile(path.join(folder,'buffs.schema.json'),JSON.stringify({$schema:base.$schema,title:'灯帰り 戦闘バフ',type:'object',additionalProperties:buff},null,2)+'\n');

const fireEffect=obj({name:string,description:string,repels:boolean,encounterRate:numeric(0,5),enemyScale:numeric(.1,5),priority:{type:'integer',minimum:0,maximum:1000}});
const fixture=obj({id:string,name:string,map:string,x:integer,y:integer,effect:string,radius:{type:'integer',minimum:0,maximum:30},capacity:{anyOf:[{type:'integer',minimum:1,maximum:100000},{type:'null'}]},initiallyLit:boolean});
const fireSystem=obj({use:{const:'fire_network'},enabled:boolean,entryFixture:string,fuelItem:string,emberItem:string,portable:obj({item:string,capacity:{type:'integer',minimum:2,maximum:100000},baseEffect:string,entryEffect:string,warnings:{type:'array',minItems:2,maxItems:2,items:{type:'integer',minimum:1}}}),threat:obj({encounter:string}),effects:{type:'object',minProperties:1,additionalProperties:fireEffect},fixtures:{type:'array',minItems:1,items:fixture}},['use','entryFixture','fuelItem','emberItem','portable','threat','effects','fixtures']);
const point={map:string,x:integer,y:integer};
const waterSystem=obj({use:{const:'waterworks'},enabled:boolean,phases:{type:'array',minItems:2,items:obj({id:string,name:string,duration:numeric(1,10000),level:{type:'integer',minimum:0,maximum:10}})},controls:{type:'array',items:obj({...point,id:string,name:string,kind:{enum:['gate','valve']},initiallyOpen:boolean})},floors:{type:'array',minItems:1,items:obj({map:string,controls:strings})},protectionItem:string,encounters:{type:'array',items:obj({min:{type:'integer',minimum:0,maximum:10},encounter:string})}},['use','phases','controls','floors','protectionItem','encounters']);
const corrosionSystem=obj({use:{const:'corrosion'},enabled:boolean,perBattle:{type:'integer',minimum:1,maximum:100},eater:obj({enemy:string,encounter:string,threshold:{type:'integer',minimum:1,maximum:100}}),washZones:{type:'array',minItems:1,items:obj(point)}},['use','perBattle','eater','washZones']);
const wallSystem=obj({use:{const:'breakable_walls'},enabled:boolean,walls:{type:'array',minItems:1,items:obj({...point,id:string,name:string,items:strings,abilities:strings})}},['use','walls']);
const dungeonArt=obj({asset:string,rect:obj({x:numeric(0,1),y:numeric(0,1),width:numeric(.0001,1),height:numeric(.0001,1)})});
const dungeon=obj({art:obj({wall:dungeonArt,device:dungeonArt,floor:dungeonArt,variants:{type:'object',additionalProperties:dungeonArt}},['wall','device']),schemaVersion:{const:1},id:string,name:string,description:string,region:{type:'integer',minimum:1},recommendedLevel:{type:'integer',minimum:1},profile:{const:'classic'},entries:obj({main:obj({map:string,point:{const:'entrance'}})}),maps:{type:'array',minItems:1,uniqueItems:true,items:string},systems:{type:'object',additionalProperties:{oneOf:[voxelSystemSchema,fireSystem,waterSystem,corrosionSystem,wallSystem,...additionalDungeonSystems()]}},source:string},['schemaVersion','id','name','description','region','recommendedLevel','profile','entries','maps','systems']);
const authoredDungeon=structuredClone(dungeon);authoredDungeon.properties.systems.additionalProperties.oneOf=[voxelSystemSchema,fireSystem,waterSystem,corrosionSystem,wallSystem,...additionalDungeonSystems(true)];
await fs.writeFile(path.join(folder,'dungeon.schema.json'),JSON.stringify({$schema:base.$schema,$defs:{value:definitions.value,expression:definitions.expression},title:'ダンジョン編集元 v1',...authoredDungeon},null,2)+'\n');
await fs.writeFile(path.join(folder,'dungeons.schema.json'),JSON.stringify({$schema:base.$schema,$defs:{value:definitions.value,expression:definitions.expression},title:'ダンジョン一覧 v1',type:'object',additionalProperties:dungeon},null,2)+'\n');

await write('dungeon-art.schema.json',{title:'ダンジョン素材原稿',...obj({schemaVersion:{const:1},assets:obj({walls:string,devices:string}),floor:dungeonArt,entries:{type:'array',items:obj({dungeon:string,floor:dungeonArt,wall:{type:'integer',minimum:0,maximum:15},device:{type:'integer',minimum:0,maximum:15}},['dungeon','wall','device'])}},['schemaVersion','assets','entries'])});
