import fs from 'node:fs/promises';
import path from 'node:path';
import {COMMANDS} from '../src/core/script.js';
const folder=path.resolve(import.meta.dirname,'../data/schemas');await fs.mkdir(folder,{recursive:true});
const string={type:'string',minLength:1},integer={type:'integer',minimum:0},boolean={type:'boolean'},value={$ref:'#/$defs/value'},expr={$ref:'#/$defs/expression'},commands={type:'array',items:{$ref:'#/$defs/command'}};
const obj=(properties,required=Object.keys(properties),additionalProperties=false)=>({type:'object',properties,required,additionalProperties});
const variants=[];
const command=(names,properties={},required=Object.keys(properties))=>{for(const name of names.split(' '))variants.push(obj({op:{const:name},...properties},['op',...required]));};
command('say narrate',{text:value,name:{type:'string'},speaker:{type:'string'}},['text']);
command('choice',{options:{type:'array',minItems:1,items:obj({id:string,text:string,condition:value,requirement:{type:'string'},commands},['id','text','commands'])}});
command('if',{condition:value,then:commands,else:commands});
command('switch',{value,cases:{type:'array',items:obj({equals:value,commands})},default:commands});
command('call',{script:string,args:{type:'object',additionalProperties:value}},['script']);command('return');
command('set add',{target:string,value});command('flag.set',{key:string,value});command('random.set',{target:string,min:{type:'integer'},max:{type:'integer'}});
command('random.branch',{branches:{type:'array',minItems:1,items:obj({weight:{type:'number',exclusiveMinimum:0},commands})}});
command('item.give item.take',{item:value,count:{oneOf:[{type:'integer',minimum:1},expr]}},['item']);command('gold.change',{amount:value});
command('actor.heal actor.damage actor.restore_mp',{target:value,amount:value});command('party.heal_all',{ratio:{type:'number',minimum:0,maximum:1}},[]);
command('party.join party.leave',{actor:string});command('status.apply status.remove',{target:value,status:string});
command('map.teleport',{map:string,x:integer,y:integer,facing:{enum:['north','east','south','west']}},['map','x','y']);command('map.reveal',{radius:integer},[]);command('facing.set',{direction:{enum:['north','east','south','west']}});
command('object.state.set',{map:string,object:string,state:{enum:['locked','open','ready']}},['map','object','state']);command('event.mark_done',{event:string});
command('battle.start',{encounter:string,on_win:commands,on_lose:commands,on_escape:commands});command('quest.accept',{quest:string});command('quest.evidence',{quest:string,key:string,text:string});command('quest.complete',{quest:string,outcome:string});
command('scene.background audio.bgm audio.se',{asset:string});command('rest',{cost:integer,ratio:{type:'number',minimum:0,maximum:1}},[]);command('town.return light.refill');command('ending.set',{title:string,text:string});
if(variants.length!==COMMANDS.size)throw Error('Schema/command registry mismatch');
const expressionVariants=[obj({ref:string}),obj({format:{type:'string'},values:{type:'object',additionalProperties:value}})];
for(const op of ['eq','ne','gt','gte','lt','lte','in','contains'])expressionVariants.push(obj({op:{const:op},left:value,right:value}));
for(const op of ['and','or','add','sub','mul','div','mod','min','max','floor','ceil','round','abs','clamp'])expressionVariants.push(obj({op:{const:op},args:{type:'array',minItems:1,items:value}}));
expressionVariants.push(obj({op:{const:'not'},arg:value}),obj({op:{const:'exists'},value}),obj({op:{const:'has_item'},item:string,count:{type:'integer',minimum:1}},['op','item']),obj({op:{const:'has_member'},actor:string}),obj({op:{const:'has_status'},actor:string,status:string}),obj({op:{const:'event_done'},event:string}),obj({op:{const:'map_discovered'},map:string,x:integer,y:integer}));
const definitions={value:{oneOf:[{type:['string','number','boolean','null']},{type:'array',items:value},expr]},expression:{oneOf:expressionVariants},command:{oneOf:variants},script:obj({commands})};
const base={"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":definitions};
const write=(name,content)=>fs.writeFile(path.join(folder,name),JSON.stringify({...base,...content},null,2)+'\n');
await write('script.schema.json',{title:'灯帰り DSL v1 スクリプト',...obj({scripts:{type:'object',additionalProperties:{$ref:'#/$defs/script'}}})});
await write('quest.schema.json',{title:'灯帰り DSL v1 クエスト',...obj({schemaVersion:{const:1},id:string,number:{type:'integer',minimum:1},title:string,client:string,brief:string,region:{type:'integer',minimum:1},type:string,recommendedLevel:{type:'integer',minimum:1},requires:value,unlockHint:{type:'string'},locations:{type:'array',minItems:3,items:obj({map:string,object:string,x:integer,y:integer,role:string})},outcomes:{type:'object',minProperties:3,additionalProperties:obj({label:string,text:string,gold:integer,xp:integer})},model:{type:'object',required:['world','agents','conflict','narrative','audience','reveal','beats']},scripts:{type:'object',additionalProperties:{$ref:'#/$defs/script'}}})});
await write('map.schema.json',{title:'灯帰り DSL v1 グリッドマップ',...obj({id:string,region:{type:'integer',minimum:1},floor:{type:'integer',minimum:1},name:string,tiles:{type:'array',minItems:3,items:{type:'string',pattern:'^[#.]+$'}},entrance:obj({x:integer,y:integer,facing:{enum:['north','east','south','west']}}),background:string,music:string,encounter:string,encounterRate:{type:'number',minimum:0,maximum:1},objects:{type:'array',items:obj({id:string,x:integer,y:integer,name:string,kind:{enum:['exit','stairs','chest','fountain','trap','door','clue','decision']},trigger:{enum:['enter','interact']},safe:boolean,once:boolean,blocking:boolean,initialState:string,condition:value,quest:string,script:string},['id','x','y','name','kind','trigger','script'])}})});
await write('game.schema.json',{title:'灯帰り DSL v1 作品マニフェスト',...obj({schemaVersion:{const:1},id:string,version:string,title:string,subtitle:string,startScript:string,initial:obj({gold:integer,members:{type:'array',minItems:1,maxItems:5,uniqueItems:true,items:string},inventory:{type:'object',additionalProperties:integer}}),services:{type:'array',items:obj({id:string,label:string,detail:string,script:string})},files:obj({databases:{type:'object',additionalProperties:string},maps:{type:'array',items:string},quests:{type:'array',items:string},scripts:{type:'array',items:string}})})});
console.log(`Generated schemas for ${COMMANDS.size} commands, game, maps and quests`);
