// Generated by tools/build-config-editors.mjs.
export const editors=[
  {
    "id": "catalog-q011-q020",
    "file": "catalog-q011-q020.json",
    "page": "catalog-q011-q020.html",
    "family": "catalog",
    "title": "q011〜q020のシナリオ原稿",
    "group": "物語",
    "hint": "本文と分岐の原稿です。ほかのクエストの本筋はauthoringのJavaScript原稿で管理しています。"
  },
  {
    "id": "cell-layers",
    "file": "cell-layers.json",
    "page": "cell-layers.html",
    "family": "cells",
    "title": "セル種・照度・セル配置",
    "group": "地形",
    "hint": "通常マップの通行値・外観・照度を決める正本です。rowsの順序はマップの座標です。"
  },
  {
    "id": "connected-maps",
    "file": "connected-maps.json",
    "page": "connected-maps.html",
    "family": "maps",
    "title": "接続済み2Dマップ",
    "group": "地形",
    "hint": "マップの基本情報と配置物を編集します。最終的な通行値はcell-layers.jsonのrowsから生成します。"
  },
  {
    "id": "dungeon-art",
    "file": "dungeon-art.json",
    "page": "dungeon-art.html",
    "family": "art",
    "title": "迷宮の壁・装置・床素材",
    "group": "素材",
    "hint": "既存の素材と切り出し位置を指定します。画像ファイルの作成は別途行います。"
  },
  {
    "id": "dungeon-content",
    "file": "dungeon-content.json",
    "page": "dungeon-content.html",
    "family": "bundle",
    "title": "追加迷宮の道具・敵・命令",
    "group": "迷宮",
    "hint": "共通の道具・敵・命令が対象です。mapsはconnected-maps.json、通行値はcell-layers.jsonの指定を優先します。"
  },
  {
    "id": "entities",
    "file": "entities.json",
    "page": "entities.html",
    "family": "entities",
    "title": "仲間と追加魔物",
    "group": "隊・戦闘",
    "hint": "仲間の能力と追加魔物を編集します。画像や全体の参照整合は再生成後に確認します。"
  },
  {
    "id": "jobs",
    "file": "jobs.json",
    "page": "jobs.html",
    "family": "jobs",
    "title": "職業・技能・装備",
    "group": "隊・戦闘",
    "hint": "職業、技能、消費、効果、初期職業、店の追加商品を編集します。"
  },
  {
    "id": "kagaribi-content",
    "file": "kagaribi-content.json",
    "page": "kagaribi-content.html",
    "family": "bundle",
    "title": "篝火の道具・敵・命令",
    "group": "迷宮",
    "hint": "火台は迷宮設定、壁灯はクエスト配置です。篝火マップの基本情報はこのJSON、通行値はcell-layers.jsonを編集します。"
  },
  {
    "id": "locations",
    "file": "locations.json",
    "page": "locations.html",
    "family": "locations",
    "title": "町の場所と施設",
    "group": "町",
    "hint": "場所の親子関係、出入口、施設サービスを編集します。"
  },
  {
    "id": "presentation",
    "file": "presentation.json",
    "page": "presentation.html",
    "family": "presentation",
    "title": "演出・SE・操作との対応",
    "group": "素材",
    "hint": "演出と音の設定です。音符を変えた場合は音声素材も別途再生成してください。"
  },
  {
    "id": "terrain-content",
    "file": "terrain-content.json",
    "page": "terrain-content.html",
    "family": "terrain",
    "title": "地形の補助設定",
    "group": "地形",
    "hint": "道具・店の追加商品と互換用の開口原稿です。接続済み2Dマップの通行値はcell-layers.jsonを編集してください。"
  },
  {
    "id": "voxel-content",
    "file": "voxel-content.json",
    "page": "voxel-content.html",
    "family": "voxel",
    "title": "退避中の3D地形原稿",
    "group": "互換原稿",
    "hint": "通常の2Dゲームには読み込まれない互換原稿です。編集しても通常マップの形状は変わりません。"
  },
  {
    "id": "kagaribi",
    "file": "dungeons/kagaribi.json",
    "page": "dungeons/kagaribi.html",
    "family": "dungeon",
    "title": "篝火の迷宮",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "moving_village",
    "file": "dungeons/moving_village.json",
    "page": "dungeons/moving_village.html",
    "family": "dungeon",
    "title": "巨獣上の移動集落",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "prayerless_valley",
    "file": "dungeons/prayerless_valley.json",
    "page": "dungeons/prayerless_valley.html",
    "family": "dungeon",
    "title": "祈りの届かない谷",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_1",
    "file": "dungeons/region_1.json",
    "page": "dungeons/region_1.html",
    "family": "dungeon",
    "title": "灯守の地下水道",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_10",
    "file": "dungeons/region_10.json",
    "page": "dungeons/region_10.html",
    "family": "dungeon",
    "title": "帰還者の深淵",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_2",
    "file": "dungeons/region_2.json",
    "page": "dungeons/region_2.html",
    "family": "dungeon",
    "title": "塩哭きの廃坑",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_3",
    "file": "dungeons/region_3.json",
    "page": "dungeons/region_3.html",
    "family": "dungeon",
    "title": "根喰みの地下庭園",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_4",
    "file": "dungeons/region_4.json",
    "page": "dungeons/region_4.html",
    "family": "dungeon",
    "title": "鏡沈みの礼拝堂",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_5",
    "file": "dungeons/region_5.json",
    "page": "dungeons/region_5.html",
    "family": "dungeon",
    "title": "灰時計の書庫",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_6",
    "file": "dungeons/region_6.json",
    "page": "dungeons/region_6.html",
    "family": "dungeon",
    "title": "眠れる地下市場",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_7",
    "file": "dungeons/region_7.json",
    "page": "dungeons/region_7.html",
    "family": "dungeon",
    "title": "黒潮の沈没城",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_8",
    "file": "dungeons/region_8.json",
    "page": "dungeons/region_8.html",
    "family": "dungeon",
    "title": "鉄胎の機関廟",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "region_9",
    "file": "dungeons/region_9.json",
    "page": "dungeons/region_9.html",
    "family": "dungeon",
    "title": "星欠けの地下観測所",
    "group": "迷宮の仕掛け",
    "hint": "火・水位・接続・装置・条件付きイベントなどを編集します。"
  },
  {
    "id": "q001",
    "file": "quests/q001.events.json",
    "page": "quests/q001.events.html",
    "family": "quest",
    "title": "q001 帰らない灯番",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q002",
    "file": "quests/q002.events.json",
    "page": "quests/q002.events.html",
    "family": "quest",
    "title": "q002 骨の荷札",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q003",
    "file": "quests/q003.events.json",
    "page": "quests/q003.events.html",
    "family": "quest",
    "title": "q003 逆流する鐘",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q004",
    "file": "quests/q004.events.json",
    "page": "quests/q004.events.html",
    "family": "quest",
    "title": "q004 二枚目の通行証",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q005",
    "file": "quests/q005.events.json",
    "page": "quests/q005.events.html",
    "family": "quest",
    "title": "q005 甘い排水",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q006",
    "file": "quests/q006.events.json",
    "page": "quests/q006.events.html",
    "family": "quest",
    "title": "q006 沈んだ給金箱",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q007",
    "file": "quests/q007.events.json",
    "page": "quests/q007.events.html",
    "family": "quest",
    "title": "q007 声を返す壁",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q008",
    "file": "quests/q008.events.json",
    "page": "quests/q008.events.html",
    "family": "quest",
    "title": "q008 浮かばない棺",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q009",
    "file": "quests/q009.events.json",
    "page": "quests/q009.events.html",
    "family": "quest",
    "title": "q009 鼠の避難路",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q010",
    "file": "quests/q010.events.json",
    "page": "quests/q010.events.html",
    "family": "quest",
    "title": "q010 最後の水門番",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q011",
    "file": "quests/q011.events.json",
    "page": "quests/q011.events.html",
    "family": "quest",
    "title": "q011 塩の花嫁",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q012",
    "file": "quests/q012.events.json",
    "page": "quests/q012.events.html",
    "family": "quest",
    "title": "q012 三つのつるはし",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q013",
    "file": "quests/q013.events.json",
    "page": "quests/q013.events.html",
    "family": "quest",
    "title": "q013 呼吸する鉱脈",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q014",
    "file": "quests/q014.events.json",
    "page": "quests/q014.events.html",
    "family": "quest",
    "title": "q014 帰りの貨車",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q015",
    "file": "quests/q015.events.json",
    "page": "quests/q015.events.html",
    "family": "quest",
    "title": "q015 泣く塩柱",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q016",
    "file": "quests/q016.events.json",
    "page": "quests/q016.events.html",
    "family": "quest",
    "title": "q016 無音の発破",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q017",
    "file": "quests/q017.events.json",
    "page": "quests/q017.events.html",
    "family": "quest",
    "title": "q017 二度掘られた墓",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q018",
    "file": "quests/q018.events.json",
    "page": "quests/q018.events.html",
    "family": "quest",
    "title": "q018 白い借金",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q019",
    "file": "quests/q019.events.json",
    "page": "quests/q019.events.html",
    "family": "quest",
    "title": "q019 底なしの計量器",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q020",
    "file": "quests/q020.events.json",
    "page": "quests/q020.events.html",
    "family": "quest",
    "title": "q020 坑道の王冠",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q021",
    "file": "quests/q021.events.json",
    "page": "quests/q021.events.html",
    "family": "quest",
    "title": "q021 種を盗む鳥",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q022",
    "file": "quests/q022.events.json",
    "page": "quests/q022.events.html",
    "family": "quest",
    "title": "q022 緑の寝息",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q023",
    "file": "quests/q023.events.json",
    "page": "quests/q023.events.html",
    "family": "quest",
    "title": "q023 母樹の指輪",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q024",
    "file": "quests/q024.events.json",
    "page": "quests/q024.events.html",
    "family": "quest",
    "title": "q024 食べられる地図",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q025",
    "file": "quests/q025.events.json",
    "page": "quests/q025.events.html",
    "family": "quest",
    "title": "q025 地下の雨乞い",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q026",
    "file": "quests/q026.events.json",
    "page": "quests/q026.events.html",
    "family": "quest",
    "title": "q026 実らない約束",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q027",
    "file": "quests/q027.events.json",
    "page": "quests/q027.events.html",
    "family": "quest",
    "title": "q027 花粉の身代金",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q028",
    "file": "quests/q028.events.json",
    "page": "quests/q028.events.html",
    "family": "quest",
    "title": "q028 庭師の空席",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q029",
    "file": "quests/q029.events.json",
    "page": "quests/q029.events.html",
    "family": "quest",
    "title": "q029 赤い蜜の契約",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q030",
    "file": "quests/q030.events.json",
    "page": "quests/q030.events.html",
    "family": "quest",
    "title": "q030 根の向こうの朝",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q031",
    "file": "quests/q031.events.json",
    "page": "quests/q031.events.html",
    "family": "quest",
    "title": "q031 遅れる祈り",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q032",
    "file": "quests/q032.events.json",
    "page": "quests/q032.events.html",
    "family": "quest",
    "title": "q032 片目の聖像",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q033",
    "file": "quests/q033.events.json",
    "page": "quests/q033.events.html",
    "family": "quest",
    "title": "q033 映らない巡礼者",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q034",
    "file": "quests/q034.events.json",
    "page": "quests/q034.events.html",
    "family": "quest",
    "title": "q034 赦しの領収書",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q035",
    "file": "quests/q035.events.json",
    "page": "quests/q035.events.html",
    "family": "quest",
    "title": "q035 鏡の向こうの施し",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q036",
    "file": "quests/q036.events.json",
    "page": "quests/q036.events.html",
    "family": "quest",
    "title": "q036 七番目の歌声",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q037",
    "file": "quests/q037.events.json",
    "page": "quests/q037.events.html",
    "family": "quest",
    "title": "q037 夜だけの告解",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q038",
    "file": "quests/q038.events.json",
    "page": "quests/q038.events.html",
    "family": "quest",
    "title": "q038 聖水の沈殿",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q039",
    "file": "quests/q039.events.json",
    "page": "quests/q039.events.html",
    "family": "quest",
    "title": "q039 顔を売る仮面",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q040",
    "file": "quests/q040.events.json",
    "page": "quests/q040.events.html",
    "family": "quest",
    "title": "q040 砕けない祈り",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q041",
    "file": "quests/q041.events.json",
    "page": "quests/q041.events.html",
    "family": "quest",
    "title": "q041 返却日のない本",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q042",
    "file": "quests/q042.events.json",
    "page": "quests/q042.events.html",
    "family": "quest",
    "title": "q042 砂時計の残業",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q043",
    "file": "quests/q043.events.json",
    "page": "quests/q043.events.html",
    "family": "quest",
    "title": "q043 墨を食う火",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q044",
    "file": "quests/q044.events.json",
    "page": "quests/q044.events.html",
    "family": "quest",
    "title": "q044 未来の訃報",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q045",
    "file": "quests/q045.events.json",
    "page": "quests/q045.events.html",
    "family": "quest",
    "title": "q045 白紙の相続",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q046",
    "file": "quests/q046.events.json",
    "page": "quests/q046.events.html",
    "family": "quest",
    "title": "q046 迷子の索引",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q047",
    "file": "quests/q047.events.json",
    "page": "quests/q047.events.html",
    "family": "quest",
    "title": "q047 一頁の戦争",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q048",
    "file": "quests/q048.events.json",
    "page": "quests/q048.events.html",
    "family": "quest",
    "title": "q048 眠る校正者",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q049",
    "file": "quests/q049.events.json",
    "page": "quests/q049.events.html",
    "family": "quest",
    "title": "q049 忘却の栞",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q050",
    "file": "quests/q050.events.json",
    "page": "quests/q050.events.html",
    "family": "quest",
    "title": "q050 止まった終章",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q051",
    "file": "quests/q051.events.json",
    "page": "quests/q051.events.html",
    "family": "quest",
    "title": "q051 釣銭のない店",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q052",
    "file": "quests/q052.events.json",
    "page": "quests/q052.events.html",
    "family": "quest",
    "title": "q052 幽霊の競り札",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q053",
    "file": "quests/q053.events.json",
    "page": "quests/q053.events.html",
    "family": "quest",
    "title": "q053 賞味期限の明日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q054",
    "file": "quests/q054.events.json",
    "page": "quests/q054.events.html",
    "family": "quest",
    "title": "q054 夢の質草",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q055",
    "file": "quests/q055.events.json",
    "page": "quests/q055.events.html",
    "family": "quest",
    "title": "q055 値札のついた影",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q056",
    "file": "quests/q056.events.json",
    "page": "quests/q056.events.html",
    "family": "quest",
    "title": "q056 閉店後の拍手",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q057",
    "file": "quests/q057.events.json",
    "page": "quests/q057.events.html",
    "family": "quest",
    "title": "q057 無主の露店",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q058",
    "file": "quests/q058.events.json",
    "page": "quests/q058.events.html",
    "family": "quest",
    "title": "q058 金貨の病",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q059",
    "file": "quests/q059.events.json",
    "page": "quests/q059.events.html",
    "family": "quest",
    "title": "q059 一人分の祝宴",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q060",
    "file": "quests/q060.events.json",
    "page": "quests/q060.events.html",
    "family": "quest",
    "title": "q060 市場の目覚まし",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q061",
    "file": "quests/q061.events.json",
    "page": "quests/q061.events.html",
    "family": "quest",
    "title": "q061 濡れない海図",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q062",
    "file": "quests/q062.events.json",
    "page": "quests/q062.events.html",
    "family": "quest",
    "title": "q062 王の救命胴衣",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q063",
    "file": "quests/q063.events.json",
    "page": "quests/q063.events.html",
    "family": "quest",
    "title": "q063 潮に逆らう階段",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q064",
    "file": "quests/q064.events.json",
    "page": "quests/q064.events.html",
    "family": "quest",
    "title": "q064 届く砲声",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q065",
    "file": "quests/q065.events.json",
    "page": "quests/q065.events.html",
    "family": "quest",
    "title": "q065 水中の火葬",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q066",
    "file": "quests/q066.events.json",
    "page": "quests/q066.events.html",
    "family": "quest",
    "title": "q066 珊瑚の軍議",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q067",
    "file": "quests/q067.events.json",
    "page": "quests/q067.events.html",
    "family": "quest",
    "title": "q067 人魚の筆談",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q068",
    "file": "quests/q068.events.json",
    "page": "quests/q068.events.html",
    "family": "quest",
    "title": "q068 二つの錨",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q069",
    "file": "quests/q069.events.json",
    "page": "quests/q069.events.html",
    "family": "quest",
    "title": "q069 海王の通行税",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q070",
    "file": "quests/q070.events.json",
    "page": "quests/q070.events.html",
    "family": "quest",
    "title": "q070 沈没城の浮上",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q071",
    "file": "quests/q071.events.json",
    "page": "quests/q071.events.html",
    "family": "quest",
    "title": "q071 止まれない門番",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q072",
    "file": "quests/q072.events.json",
    "page": "quests/q072.events.html",
    "family": "quest",
    "title": "q072 油の洗礼",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q073",
    "file": "quests/q073.events.json",
    "page": "quests/q073.events.html",
    "family": "quest",
    "title": "q073 天使の予備腕",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q074",
    "file": "quests/q074.events.json",
    "page": "quests/q074.events.html",
    "family": "quest",
    "title": "q074 祈祷の順番",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q075",
    "file": "quests/q075.events.json",
    "page": "quests/q075.events.html",
    "family": "quest",
    "title": "q075 無給の聖者",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q076",
    "file": "quests/q076.events.json",
    "page": "quests/q076.events.html",
    "family": "quest",
    "title": "q076 鉄の子守歌",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q077",
    "file": "quests/q077.events.json",
    "page": "quests/q077.events.html",
    "family": "quest",
    "title": "q077 聖痕の配線",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q078",
    "file": "quests/q078.events.json",
    "page": "quests/q078.events.html",
    "family": "quest",
    "title": "q078 部品の記憶",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q079",
    "file": "quests/q079.events.json",
    "page": "quests/q079.events.html",
    "family": "quest",
    "title": "q079 九十九回の再起動",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q080",
    "file": "quests/q080.events.json",
    "page": "quests/q080.events.html",
    "family": "quest",
    "title": "q080 鉄胎の継承",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q081",
    "file": "quests/q081.events.json",
    "page": "quests/q081.events.html",
    "family": "quest",
    "title": "q081 落ちてこない星",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q082",
    "file": "quests/q082.events.json",
    "page": "quests/q082.events.html",
    "family": "quest",
    "title": "q082 星売りの空瓶",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q083",
    "file": "quests/q083.events.json",
    "page": "quests/q083.events.html",
    "family": "quest",
    "title": "q083 地底の日食",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q084",
    "file": "quests/q084.events.json",
    "page": "quests/q084.events.html",
    "family": "quest",
    "title": "q084 帰還信号",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q085",
    "file": "quests/q085.events.json",
    "page": "quests/q085.events.html",
    "family": "quest",
    "title": "q085 方位のない羅針盤",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q086",
    "file": "quests/q086.events.json",
    "page": "quests/q086.events.html",
    "family": "quest",
    "title": "q086 百年前の観測者",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q087",
    "file": "quests/q087.events.json",
    "page": "quests/q087.events.html",
    "family": "quest",
    "title": "q087 願いを消す流星",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q088",
    "file": "quests/q088.events.json",
    "page": "quests/q088.events.html",
    "family": "quest",
    "title": "q088 観測窓の亀裂",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q089",
    "file": "quests/q089.events.json",
    "page": "quests/q089.events.html",
    "family": "quest",
    "title": "q089 逆さまの天球儀",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q090",
    "file": "quests/q090.events.json",
    "page": "quests/q090.events.html",
    "family": "quest",
    "title": "q090 空を返す日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q091",
    "file": "quests/q091.events.json",
    "page": "quests/q091.events.html",
    "family": "quest",
    "title": "q091 先に帰った足跡",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q092",
    "file": "quests/q092.events.json",
    "page": "quests/q092.events.html",
    "family": "quest",
    "title": "q092 出口を持つ獣",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q093",
    "file": "quests/q093.events.json",
    "page": "quests/q093.events.html",
    "family": "quest",
    "title": "q093 名を置く宿",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q094",
    "file": "quests/q094.events.json",
    "page": "quests/q094.events.html",
    "family": "quest",
    "title": "q094 帰還税",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q095",
    "file": "quests/q095.events.json",
    "page": "quests/q095.events.html",
    "family": "quest",
    "title": "q095 英雄の空白",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q096",
    "file": "quests/q096.events.json",
    "page": "quests/q096.events.html",
    "family": "quest",
    "title": "q096 忘れ物の隊列",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q097",
    "file": "quests/q097.events.json",
    "page": "quests/q097.events.html",
    "family": "quest",
    "title": "q097 生者の点呼",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q098",
    "file": "quests/q098.events.json",
    "page": "quests/q098.events.html",
    "family": "quest",
    "title": "q098 最後の一室",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q099",
    "file": "quests/q099.events.json",
    "page": "quests/q099.events.html",
    "family": "quest",
    "title": "q099 帰らぬ者の灯",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q100",
    "file": "quests/q100.events.json",
    "page": "quests/q100.events.html",
    "family": "quest",
    "title": "q100 百の帰還",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q101",
    "file": "quests/q101.events.json",
    "page": "quests/q101.events.html",
    "family": "quest",
    "title": "q101 三度目の戸締まり",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q102",
    "file": "quests/q102.events.json",
    "page": "quests/q102.events.html",
    "family": "quest",
    "title": "q102 弔鐘は誰のために",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q103",
    "file": "quests/q103.events.json",
    "page": "quests/q103.events.html",
    "family": "quest",
    "title": "q103 一枚多い食券",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q104",
    "file": "quests/q104.events.json",
    "page": "quests/q104.events.html",
    "family": "quest",
    "title": "q104 雨を売る少年",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q105",
    "file": "quests/q105.events.json",
    "page": "quests/q105.events.html",
    "family": "quest",
    "title": "q105 花嫁の片方の靴",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q106",
    "file": "quests/q106.events.json",
    "page": "quests/q106.events.html",
    "family": "quest",
    "title": "q106 パン泥棒の影",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q107",
    "file": "quests/q107.events.json",
    "page": "quests/q107.events.html",
    "family": "quest",
    "title": "q107 六人目の客",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q108",
    "file": "quests/q108.events.json",
    "page": "quests/q108.events.html",
    "family": "quest",
    "title": "q108 猫に付いた懸賞",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q109",
    "file": "quests/q109.events.json",
    "page": "quests/q109.events.html",
    "family": "quest",
    "title": "q109 火のない鍛冶場",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q110",
    "file": "quests/q110.events.json",
    "page": "quests/q110.events.html",
    "family": "quest",
    "title": "q110 明日までの英雄",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q111",
    "file": "quests/q111.events.json",
    "page": "quests/q111.events.html",
    "family": "quest",
    "title": "q111 白旗の荷馬車",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q112",
    "file": "quests/q112.events.json",
    "page": "quests/q112.events.html",
    "family": "quest",
    "title": "q112 置いていく灯",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q113",
    "file": "quests/q113.events.json",
    "page": "quests/q113.events.html",
    "family": "quest",
    "title": "q113 雪解けを待たない男",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q114",
    "file": "quests/q114.events.json",
    "page": "quests/q114.events.html",
    "family": "quest",
    "title": "q114 二人分の通行料",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q115",
    "file": "quests/q115.events.json",
    "page": "quests/q115.events.html",
    "family": "quest",
    "title": "q115 追手のいない逃亡",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q116",
    "file": "quests/q116.events.json",
    "page": "quests/q116.events.html",
    "family": "quest",
    "title": "q116 帰り道だけの地図",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q117",
    "file": "quests/q117.events.json",
    "page": "quests/q117.events.html",
    "family": "quest",
    "title": "q117 空の棺の護送",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q118",
    "file": "quests/q118.events.json",
    "page": "quests/q118.events.html",
    "family": "quest",
    "title": "q118 聞こえない救難笛",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q119",
    "file": "quests/q119.events.json",
    "page": "quests/q119.events.html",
    "family": "quest",
    "title": "q119 寝返りの見張り",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q120",
    "file": "quests/q120.events.json",
    "page": "quests/q120.events.html",
    "family": "quest",
    "title": "q120 最後尾の旗",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q121",
    "file": "quests/q121.events.json",
    "page": "quests/q121.events.html",
    "family": "quest",
    "title": "q121 百匹目の狼",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q122",
    "file": "quests/q122.events.json",
    "page": "quests/q122.events.html",
    "family": "quest",
    "title": "q122 逃げた竜殺し",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q123",
    "file": "quests/q123.events.json",
    "page": "quests/q123.events.html",
    "family": "quest",
    "title": "q123 討伐数ゼロの勲章",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q124",
    "file": "quests/q124.events.json",
    "page": "quests/q124.events.html",
    "family": "quest",
    "title": "q124 二度死んだ大猪",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q125",
    "file": "quests/q125.events.json",
    "page": "quests/q125.events.html",
    "family": "quest",
    "title": "q125 弓を置く日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q126",
    "file": "quests/q126.events.json",
    "page": "quests/q126.events.html",
    "family": "quest",
    "title": "q126 獲物のいない狩猟祭",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q127",
    "file": "quests/q127.events.json",
    "page": "quests/q127.events.html",
    "family": "quest",
    "title": "q127 魔物の借金",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q128",
    "file": "quests/q128.events.json",
    "page": "quests/q128.events.html",
    "family": "quest",
    "title": "q128 鎧を食う蛾",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q129",
    "file": "quests/q129.events.json",
    "page": "quests/q129.events.html",
    "family": "quest",
    "title": "q129 傷を見せない隊長",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q130",
    "file": "quests/q130.events.json",
    "page": "quests/q130.events.html",
    "family": "quest",
    "title": "q130 最弱の王",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q131",
    "file": "quests/q131.events.json",
    "page": "quests/q131.events.html",
    "family": "quest",
    "title": "q131 逆向きの足跡",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q132",
    "file": "quests/q132.events.json",
    "page": "quests/q132.events.html",
    "family": "quest",
    "title": "q132 宝箱の底の椅子",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q133",
    "file": "quests/q133.events.json",
    "page": "quests/q133.events.html",
    "family": "quest",
    "title": "q133 一段足りない階段",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q134",
    "file": "quests/q134.events.json",
    "page": "quests/q134.events.html",
    "family": "quest",
    "title": "q134 敗者の宝物庫",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q135",
    "file": "quests/q135.events.json",
    "page": "quests/q135.events.html",
    "family": "quest",
    "title": "q135 水底の朝食",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q136",
    "file": "quests/q136.events.json",
    "page": "quests/q136.events.html",
    "family": "quest",
    "title": "q136 翻訳しない扉",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q137",
    "file": "quests/q137.events.json",
    "page": "quests/q137.events.html",
    "family": "quest",
    "title": "q137 燃え残る図書館",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q138",
    "file": "quests/q138.events.json",
    "page": "quests/q138.events.html",
    "family": "quest",
    "title": "q138 行き止まりの探検家",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q139",
    "file": "quests/q139.events.json",
    "page": "quests/q139.events.html",
    "family": "quest",
    "title": "q139 ふたつの出口",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q140",
    "file": "quests/q140.events.json",
    "page": "quests/q140.events.html",
    "family": "quest",
    "title": "q140 迷宮の休業日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q141",
    "file": "quests/q141.events.json",
    "page": "quests/q141.events.html",
    "family": "quest",
    "title": "q141 音の出ない優勝旗",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q142",
    "file": "quests/q142.events.json",
    "page": "quests/q142.events.html",
    "family": "quest",
    "title": "q142 偽物職人の本物",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q143",
    "file": "quests/q143.events.json",
    "page": "quests/q143.events.html",
    "family": "quest",
    "title": "q143 辛くない火吹き料理",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q144",
    "file": "quests/q144.events.json",
    "page": "quests/q144.events.html",
    "family": "quest",
    "title": "q144 祭の悪役",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q145",
    "file": "quests/q145.events.json",
    "page": "quests/q145.events.html",
    "family": "quest",
    "title": "q145 花を咲かせない庭",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q146",
    "file": "quests/q146.events.json",
    "page": "quests/q146.events.html",
    "family": "quest",
    "title": "q146 染め直せない軍服",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q147",
    "file": "quests/q147.events.json",
    "page": "quests/q147.events.html",
    "family": "quest",
    "title": "q147 一番遅い配達",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q148",
    "file": "quests/q148.events.json",
    "page": "quests/q148.events.html",
    "family": "quest",
    "title": "q148 贋金より軽い金",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q149",
    "file": "quests/q149.events.json",
    "page": "quests/q149.events.html",
    "family": "quest",
    "title": "q149 売らない剣",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q150",
    "file": "quests/q150.events.json",
    "page": "quests/q150.events.html",
    "family": "quest",
    "title": "q150 大道芸人の弟子",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q151",
    "file": "quests/q151.events.json",
    "page": "quests/q151.events.html",
    "family": "quest",
    "title": "q151 暗殺者の遅刻",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q152",
    "file": "quests/q152.events.json",
    "page": "quests/q152.events.html",
    "family": "quest",
    "title": "q152 密書を読ませる仕事",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q153",
    "file": "quests/q153.events.json",
    "page": "quests/q153.events.html",
    "family": "quest",
    "title": "q153 招待されなかった伯爵",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q154",
    "file": "quests/q154.events.json",
    "page": "quests/q154.events.html",
    "family": "quest",
    "title": "q154 鍵を盗まない泥棒",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q155",
    "file": "quests/q155.events.json",
    "page": "quests/q155.events.html",
    "family": "quest",
    "title": "q155 味方の密告",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q156",
    "file": "quests/q156.events.json",
    "page": "quests/q156.events.html",
    "family": "quest",
    "title": "q156 降伏しない人質",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q157",
    "file": "quests/q157.events.json",
    "page": "quests/q157.events.html",
    "family": "quest",
    "title": "q157 影武者の休日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q158",
    "file": "quests/q158.events.json",
    "page": "quests/q158.events.html",
    "family": "quest",
    "title": "q158 成功させてはいけない救出",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q159",
    "file": "quests/q159.events.json",
    "page": "quests/q159.events.html",
    "family": "quest",
    "title": "q159 二重に売れた地図",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q160",
    "file": "quests/q160.events.json",
    "page": "quests/q160.events.html",
    "family": "quest",
    "title": "q160 拍手する裏切り者",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q161",
    "file": "quests/q161.events.json",
    "page": "quests/q161.events.html",
    "family": "quest",
    "title": "q161 治さない傷",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q162",
    "file": "quests/q162.events.json",
    "page": "quests/q162.events.html",
    "family": "quest",
    "title": "q162 騎士の盾を借りる",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q163",
    "file": "quests/q163.events.json",
    "page": "quests/q163.events.html",
    "family": "quest",
    "title": "q163 盗賊の初仕事",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q164",
    "file": "quests/q164.events.json",
    "page": "quests/q164.events.html",
    "family": "quest",
    "title": "q164 吟遊詩人抜きの宴",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q165",
    "file": "quests/q165.events.json",
    "page": "quests/q165.events.html",
    "family": "quest",
    "title": "q165 仲間を外す依頼",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q166",
    "file": "quests/q166.events.json",
    "page": "quests/q166.events.html",
    "family": "quest",
    "title": "q166 最後の一撃を譲れ",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q167",
    "file": "quests/q167.events.json",
    "page": "quests/q167.events.html",
    "family": "quest",
    "title": "q167 軍師のいない勝利",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q168",
    "file": "quests/q168.events.json",
    "page": "quests/q168.events.html",
    "family": "quest",
    "title": "q168 ふたりでひとり分の報酬",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q169",
    "file": "quests/q169.events.json",
    "page": "quests/q169.events.html",
    "family": "quest",
    "title": "q169 誰にも贈れない指輪",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q170",
    "file": "quests/q170.events.json",
    "page": "quests/q170.events.html",
    "family": "quest",
    "title": "q170 別れるための冒険",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q171",
    "file": "quests/q171.events.json",
    "page": "quests/q171.events.html",
    "family": "quest",
    "title": "q171 足音を持ち帰る",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q172",
    "file": "quests/q172.events.json",
    "page": "quests/q172.events.html",
    "family": "quest",
    "title": "q172 名前を返す井戸",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q173",
    "file": "quests/q173.events.json",
    "page": "quests/q173.events.html",
    "family": "quest",
    "title": "q173 夜だけ帰る兵士",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q174",
    "file": "quests/q174.events.json",
    "page": "quests/q174.events.html",
    "family": "quest",
    "title": "q174 泣かない葬列",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q175",
    "file": "quests/q175.events.json",
    "page": "quests/q175.events.html",
    "family": "quest",
    "title": "q175 狩人を待つ獣",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q176",
    "file": "quests/q176.events.json",
    "page": "quests/q176.events.html",
    "family": "quest",
    "title": "q176 神様の忘れ物",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q177",
    "file": "quests/q177.events.json",
    "page": "quests/q177.events.html",
    "family": "quest",
    "title": "q177 嘘をつかない鏡",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q178",
    "file": "quests/q178.events.json",
    "page": "quests/q178.events.html",
    "family": "quest",
    "title": "q178 扉の向こうの明日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q179",
    "file": "quests/q179.events.json",
    "page": "quests/q179.events.html",
    "family": "quest",
    "title": "q179 墓を増やす庭",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q180",
    "file": "quests/q180.events.json",
    "page": "quests/q180.events.html",
    "family": "quest",
    "title": "q180 最後の怪談",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q181",
    "file": "quests/q181.events.json",
    "page": "quests/q181.events.html",
    "family": "quest",
    "title": "q181 白い矢筒",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q182",
    "file": "quests/q182.events.json",
    "page": "quests/q182.events.html",
    "family": "quest",
    "title": "q182 一発も撃たない砲手",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q183",
    "file": "quests/q183.events.json",
    "page": "quests/q183.events.html",
    "family": "quest",
    "title": "q183 勝者の洗濯場",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q184",
    "file": "quests/q184.events.json",
    "page": "quests/q184.events.html",
    "family": "quest",
    "title": "q184 捕虜の鍋",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q185",
    "file": "quests/q185.events.json",
    "page": "quests/q185.events.html",
    "family": "quest",
    "title": "q185 橋を落とさない理由",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q186",
    "file": "quests/q186.events.json",
    "page": "quests/q186.events.html",
    "family": "quest",
    "title": "q186 返事のない停戦",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q187",
    "file": "quests/q187.events.json",
    "page": "quests/q187.events.html",
    "family": "quest",
    "title": "q187 旗を持たない兵士",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q188",
    "file": "quests/q188.events.json",
    "page": "quests/q188.events.html",
    "family": "quest",
    "title": "q188 帰還兵の席",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q189",
    "file": "quests/q189.events.json",
    "page": "quests/q189.events.html",
    "family": "quest",
    "title": "q189 敵国の子守歌",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q190",
    "file": "quests/q190.events.json",
    "page": "quests/q190.events.html",
    "family": "quest",
    "title": "q190 終戦翌日の魔物",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q191",
    "file": "quests/q191.events.json",
    "page": "quests/q191.events.html",
    "family": "quest",
    "title": "q191 勇者を通さない門",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q192",
    "file": "quests/q192.events.json",
    "page": "quests/q192.events.html",
    "family": "quest",
    "title": "q192 消えた依頼板",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q193",
    "file": "quests/q193.events.json",
    "page": "quests/q193.events.html",
    "family": "quest",
    "title": "q193 祈りの届かない場所",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q194",
    "file": "quests/q194.events.json",
    "page": "quests/q194.events.html",
    "family": "quest",
    "title": "q194 売れた故郷",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q195",
    "file": "quests/q195.events.json",
    "page": "quests/q195.events.html",
    "family": "quest",
    "title": "q195 魔王の畑",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q196",
    "file": "quests/q196.events.json",
    "page": "quests/q196.events.html",
    "family": "quest",
    "title": "q196 英雄の名を消す日",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q197",
    "file": "quests/q197.events.json",
    "page": "quests/q197.events.html",
    "family": "quest",
    "title": "q197 忘れられる勝利",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q198",
    "file": "quests/q198.events.json",
    "page": "quests/q198.events.html",
    "family": "quest",
    "title": "q198 旅の終わりの道標",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q199",
    "file": "quests/q199.events.json",
    "page": "quests/q199.events.html",
    "family": "quest",
    "title": "q199 帰らない依頼人",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  },
  {
    "id": "q200",
    "file": "quests/q200.events.json",
    "page": "quests/q200.events.html",
    "family": "quest",
    "title": "q200 帰還印の向こう側",
    "group": "クエスト配置",
    "hint": "配置・条件・調査用スクリプトを編集します。本筋の本文は対応するシナリオ原稿で管理します。"
  }
];
