import {editors} from './catalog.js';
const list=document.getElementById('catalog'),count=document.getElementById('count'),search=document.getElementById('search');
function card(grid,title,href,description){const link=document.createElement('a'),name=document.createElement('span'),hint=document.createElement('small');link.className='config-card';link.href=href;name.textContent=title;hint.textContent=description;link.append(name,hint);grid.append(link);}
function render(){list.replaceChildren();const query=search.value.trim().toLowerCase(),visible=editors.filter(e=>`${e.title} ${e.id} ${e.file} ${e.group}`.toLowerCase().includes(query));count.textContent=`${visible.length} / ${editors.length} 件`;
 if(!query){const section=document.createElement('section'),heading=document.createElement('h2'),grid=document.createElement('div');heading.textContent='作業を選ぶ';grid.className='catalog-grid';card(grid,'マップ編集','map.html','迷宮 → マップから地形・入口・イベント・仕掛け・接続を編集');card(grid,'セル種の管理','cell-layers.html?collection=presets','共有の通行・外観・照度を編集。全使用地点に反映');card(grid,'道具・商品の編集','terrain-content.html','道具と店の商品を編集');section.append(heading,grid);list.append(section);}
 for(const group of [...new Set(visible.map(e=>e.group))]){const section=document.createElement('section'),h=document.createElement('h2'),grid=document.createElement('div');h.textContent=group;grid.className='catalog-grid';section.append(h,grid);
  for(const e of visible.filter(e=>e.group===group)){if(!query&&['cell-layers','connected-maps','terrain-content','voxel-content'].includes(e.id))continue;const link=document.createElement('a'),title=document.createElement('span'),file=document.createElement('small');link.className='config-card';link.href=!query&&e.family==='dungeon'?'map.html?dungeon='+encodeURIComponent(e.id):e.page;title.textContent=e.title;file.textContent=e.file;link.append(title,file);grid.append(link);}if(grid.children.length)list.append(section);
 }
 if(!query){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='互換原稿・原稿別の編集';details.append(summary);const grid=document.createElement('div');grid.className='catalog-grid';for(const e of editors.filter(e=>['cell-layers','connected-maps','terrain-content','voxel-content'].includes(e.id)))card(grid,e.id==='terrain-content'?'旧形式の開口地点':e.title,e.id==='terrain-content'?e.page+'?collection=mapOpenings':e.page,e.file);details.append(grid);list.append(details);}
}
search.addEventListener('input',render);render();
