// Visual details are new art direction, not retroactive claims about the old text.
const C=(id,name,role,quests,look,goal,detail)=>({id,name,role,quests:quests.split(' '),portrait:`npc_${id}`,...(['elder','rookie','rine','accused','bearers','belt','brother','cleaners','clerks','deeppeople','eda','family'].includes(id)?{sprite:`sprite_${id}`} : {}),goal,detail,design:{...look},provenance:'q001–q010 v1.1 改稿で役割と同一性を固定。外見は今回の素材制作で設定。'});
export default [
 C('rine','リネ','灯番組合の連絡係','q001 q010',{hair:'bob',color:'teal',prop:'ledger'},'帰還者を名前で数え、取り残しを防ぐ','q001とq010は同一人物。依頼受付・救助名簿・報告を担当する。'),
 C('elder','老灯番','行方不明の灯番','q001',{hair:'bald',color:'brown',prop:'lantern',age:'old'},'新人を安全な入口へ帰し、自分も生きて戻る','本名は未設定。新人へ油を渡し、最後の壁灯の下で救助を待つ。'),
 C('rookie','新人灯番','恐怖を抱える見習い','q001',{hair:'short',color:'teal',prop:'bottle',age:'young'},'暗闇が怖い。それでも老人と探索隊を助けたい','本名は未設定。老人から受け取った油を保持する。'),
 C('rescuers','灯番救助隊','引継ぎ先の救助班','q001',{hair:'cap',color:'ochre',prop:'rope',group:true},'地図に従って未帰還者を連れ戻す','集団実体。人数や隊員名は固定せず、代表像を表示する。'),
 C('belt','ベルト','運送人','q002',{hair:'slick',color:'plum',prop:'tag'},'偽装の証拠となる荷札を回収し、一味の保険請求を通す','生存する保険加入者を失踪者として届け出た一味から、標本を遺体に見せる仕事を受けた。骨箱を地下水路へ落とし、荷札だけを回収したがっている。'),
 C('porter','運搬人','標本の運搬を請けた荷役人','q002',{hair:'band',color:'brown',prop:'rope'},'仕事を失わずに標本を返したい','保険加入者本人ではなく、ベルトの依頼で箱を運んだ証人。一味の偽装を知っているが、仕事を失うことを恐れている。証言には本人の同意が必要。'),
 C('curator','標本係','医学校の標本管理者','q002',{hair:'bun',color:'ivory',prop:'ledger',glasses:true},'標本と貸出台帳を学校へ戻す','番号照合と回収を手伝う。'),
 C('examiner','保険審査員','死亡保険の審査担当','q002',{hair:'short',color:'navy',prop:'seal',glasses:true},'標本番号・荷札・失踪届・保険請求書・証言を照合する','審査所で失踪届と保険請求書を管理する。医学校の台帳、書き換えられた荷札、運搬人の証言を照合して不正を立証する。'),
 C('sora','ソラ','水門役人','q003',{hair:'tied',color:'navy',prop:'bell'},'警報の信頼を取り戻す','鐘の機構を見張り、運用試験を担当する。'),
 C('passers','通行人たち','低い通路の利用者','q003',{hair:'hood',color:'brown',prop:'bag',group:true},'荷とともに安全な通路へ出る','集団実体。鐘を止める前に高所へ誘導する。'),
 C('innkeeper','宿屋の主人','私設汚水槽の管理者','q003',{hair:'bald',color:'ochre',prop:'key'},'宿の営業と湯替えを維持する','浴場・洗濯場・食堂の拡張で増えた使用済みの水を夜にまとめて排出していた。使用量の削減と排水時刻の分散を交渉する当事者。'),
 C('seller','水売り','井戸水を樽で届ける商人','q003',{hair:'braid',color:'teal',prop:'bottle'},'水の商いによる収入を保つ','宿へ届ける水の量が減れば収入も減る。'),
 C('waterwatch','水位見張り当番','水位観測と伝令の担当','q003',{hair:'cap',color:'navy',prop:'bell',group:true},'高所の鐘へ水位を伝える','人手で鳴らす警報に必要な交代制の集団。'),
 C('ina','イナ','見習い冒険者','q004',{hair:'short',color:'ochre',prop:'paper',age:'young'},'関所に留置された姉を助ける','写しを持つ妹。姉の原本と同じ資格番号を使った。'),
 C('sister','イナの姉','留置された通行者','q004',{hair:'tied',color:'ochre',prop:'bag'},'妹を守り、自分も外へ戻る','原本の資格者。本名は未設定。'),
 C('passkeeper','関所番','地下関所の係員','q004',{hair:'cap',color:'navy',prop:'key',age:'old'},'兄の名で続けた勤務を失いたくない','水門番とは別人。死んだ兄は歴史上の人物で、生存NPCではない。'),
 C('reviewer','名義審査官','地上の資格審査担当','q004',{hair:'bun',color:'plum',prop:'seal'},'本人と資格名義を照合する','現場へ赴き申告を確認し、姉妹の仮証を発行する。'),
 C('toto','トト','菓子職人','q005',{hair:'cap',color:'ivory',prop:'scoop'},'詰まりを取り除き、工房を再開する','冷水試験の後に初めて、安全に食用へ回せるなら菌床を残したいと申し出る。分離槽の維持や、網を使う場合の清掃当番を引き受ける。'),
 C('garo','ガロ','工事頭','q006',{hair:'slick',color:'brown',prop:'ledger'},'未払いを隠し、石入りの給金箱を未開封で取り戻す','工事費を使い切り、自ら石入りの箱を沈めて盗難に見せかけた。職人たちに第三者の捜索を求められて依頼する。一部払いには自分の荷車と予備工具を売る。'),
 C('workers','工事の職人たち','未払い給金を待つ集団','q006',{hair:'band',color:'ochre',prop:'hammer',group:true},'未払いを受け取り、仲間への疑いを解く','証拠を引き受けた場合は自分たちで交渉する。'),
 C('accused','疑われた荷役人','給金箱の紛失を責められた人','q006',{hair:'curly',color:'brown',prop:'hammer',age:'young'},'盗みの疑いを晴らす','空の箱を最後に運んだが、盗んでも沈めてもいない。集団とは別の実体として所在を管理する。'),
 C('mire','ミレ','酒場で働く遺族','q007',{hair:'bob',color:'plum',prop:'letter'},'亡夫の声の正体を自分で確かめる','夫は故人。弟との面会や伝声口の封鎖を本人が選ぶ。'),
 C('brother','ミレの夫の弟','手紙を預かる遺族','q007',{hair:'curly',color:'navy',prop:'letter'},'兄の手紙を届けたいが、ミレに拒まれるのが怖い','遺品から見つけた兄の未配達の手紙の原本を保持する。似た声を兄の話し方へ寄せ、伝声管を通して読んでいた。'),
 C('yoru','ヨル','葬送組合の担当者','q008',{hair:'hood',color:'plum',prop:'incense'},'葬儀を終え、下流へ食料も届ける','遺体を納める内室と別の外底に食料を隠した。'),
 C('family','棺の遺族','水葬を待つ家族','q008',{hair:'hood',color:'navy',prop:'flower',group:true},'故人を弔い、扱いを自分たちで決める','外底の検査と葬儀の延期には了承を得る。'),
 C('bearers','棺の担ぎ手','葬送作業の担当者','q008',{hair:'band',color:'brown',prop:'rope',group:true},'棺と遺体を傷めずに運ぶ','棺の移動経路を家族や食料と分けて管理する。'),
 C('recipient','下流の受取人','避難民側の食料受取担当','q008',{hair:'braid',color:'brown',prop:'bowl'},'食料を受け取り、待つ人々へ配る','下流の葬送桟橋で待つ。棺が届いた場合は外底だけを外し、遺体を封じた内室を水葬経路へ戻す。岸や窓口へは案内に従って移動する。'),
 C('inspector','輸送検査官','食料輸送の検査担当','q008',{hair:'short',color:'teal',prop:'seal'},'今回の荷と届け先を確かめる','臨時許可を審査する。恒久的な制度変更はここでは決定しない。'),
 C('eda','エダ','地下測量士','q009',{hair:'tied',color:'teal',prop:'map',glasses:true},'鼠の異変と構造物の危険を切り分ける','旧図、支柱の測点、亀裂、地下水位を比較する。この区画に新しい変位がないことを、他区画の安全と混同しない。'),
 C('cleaners','清掃係','石灰消毒の担当者','q009',{hair:'cap',color:'ivory',prop:'brush',group:true},'担当区画を清潔に保つ','合意した区画表は保存する。散布済みの薬は元に戻らない。'),
 C('storekeeper','穀倉番','穀物庫の管理者','q009',{hair:'bald',color:'ochre',prop:'key',age:'old'},'鼠から穀物を守る','内扉を閉め、穀物への侵入を防いでいる。'),
 C('clerks','共同倉庫の受入れ係','数量と配分の記録担当','q009',{hair:'bun',color:'teal',prop:'ledger',group:true},'搬入数と出庫先を公開して管理する','穀物を受け取った事実を記録する集団。'),
 C('gatekeeper','水門番','老朽水門の操作担当','q010',{hair:'bald',color:'navy',prop:'wheel',age:'old'},'命令と取り残した住民の間で責任を決める','関所番とは別人。安全側の操作室から閉門し、操作梯子で地上へ脱出できる。旧工事用の縦坑は上下両端の検査が済むまで避難路に使えない。未承認工事と閉門を遅らせた理由を証言できる。'),
 C('nearpeople','手前の住民三人','避難通路で待つ住民','q010',{hair:'hood',color:'ochre',prop:'bag',group:true},'三人で地上へ出る','人数三人を固定。地上到着前に救出済みにしない。'),
 C('deeppeople','奥の住民二人','作業区画で待つ住民','q010',{hair:'band',color:'teal',prop:'bag',group:true},'渡りを越えて地上へ出る','人数二人を固定。渡りには救助縄が必要。'),
 C('pumpcrew','排水隊','閉門を延期する交代班','q010',{hair:'cap',color:'ochre',prop:'wheel',group:true},'現場を引き受け、避難の時間を稼ぐ','連絡だけで引継ぎ済みとせず、操作室への到着を確認する。')
];
