import {story,O,move,give,set,see,when,and,or,not} from './story-kit.mjs';
const rows=[];
{
 const s=story(6,{landing:'沈没船の船着場',water:'船底の浅瀬',shore:'荷役人の待機岸',office:'ガロの事務所'},[['landing','water'],['landing','shore'],['shore','office']]);
 s.entity('garo','landing','garo').entity('workers','shore','workers',{kind:'group'}).entity('accused','shore','accused').entity('box','water').entity('ledger','office').entity('stones','box');
 for(const k of ['opened','witnessed','ledgerRead','handed','partialPaid','delegated','report'])s.bool(k);
 s.fact('stones','給金箱に金ではなく石が入っていた').fact('debt','台帳には未払い給金があり、盗難額とされていた');
 s.past=['ガロは未払いの給金を盗難に見せ、箱を石で重くして沈めた。疑われた荷役人は金を持っていない。'];s.progression='私的な返却は証明を隠す。途中で撤回するなら箱を取り戻す必要がある。公開交渉と証拠の引渡しを分ける。';
 s.node('entry','landing',['garo'],'「給金箱だけ戻せ」。ガロは岸の荷役人を見ずに言った。彼らは一人の仲間を盗人と疑いながら、支払いを待っている。',[O('lift','縄で箱を引き上げ、船底の魔物を退ける','box',[move('party','landing','water'),give('box','water','party'),move('party','water','landing'),set('opened'),see('stones','stones')],{cost:{rope:1},combat:true}),O('witness','荷役人に沈没位置を伝え、彼らの道具で一緒に回収する','accounts',[move('party','landing','shore'),move('party workers accused','shore','landing','water'),give('box','water','party'),move('party workers accused','water','landing','shore'),set('opened'),set('witnessed'),see('stones','stones')])]);
 s.node('box','landing',['garo'],'蓋の隙間から転がったのは石だった。ガロは「金を抜いた奴が入れた」と言い、箱を求める。あなたはまだ台帳を見ていない。',[O('return','箱をガロへ返し、岸の問いを聞く','private',[give('box','party','garo'),set('handed')]),O('public','箱を保持し、荷役人の前で開く','accounts',[move('party','landing','shore'),set('witnessed')])]);
 s.node('private','landing',['garo'],'箱はガロの足元にある。岸から「中身はあったのか」と声が届いた。ここで立ち去れば、ガロの説明だけが残る。',[O('leave','箱を返した仕事として報告を終える','@contract',[set('report')]),O('retract','報告を保留し、箱を返してもらって荷役人の前へ運ぶ','accounts',[give('box','garo','party'),set('handed',false),move('party','landing','shore'),set('witnessed')])]);
 s.node('accounts','shore',['workers','accused'],'箱から石を出すと、疑われた荷役人が息をついた。「これだけで、俺じゃないと決まるのか」。未払いと盗難の区別には、ガロの台帳が要る。',[O('ledger','ガロに同行を求め、全員で事務所の台帳を確かめる','ledger',[move('party','shore','landing'),move('party garo','landing','shore'),move('party garo workers accused','shore','office'),see('debt','ledger'),give('ledger','office','party'),set('ledgerRead'),move('party garo workers accused','office','shore')])]);
 s.node('ledger','shore',['garo','workers','accused'],'台帳の未払い額が、盗まれたとされた金額と重なる。ガロは盗難を装ったと認めた。箱と台帳は、まだあなたが保持している。',[O('settle','道具の売却による一部払いを全員の前で成立させる','@informed',[set('partialPaid'),give('box','party','workers'),give('ledger','party','workers'),set('report')]),O('delegate','箱・台帳・目撃報告を荷役人へ渡し、交渉を委ねる','@compromise',[give('box','party','workers'),give('ledger','party','workers'),set('delegated'),set('report')])]);
 s.end('informed','台帳を開き一部払いを成立させる','ガロは盗難の説明を撤回し、荷役道具を売って給金の一部を払った。疑われた仲間は潔白になったが、残額と仕事の停止が残る。',and(s.is('witnessed'),s.is('ledgerRead'),s.is('partialPaid'),s.is('report')));
 s.end('contract','給金箱を私的に返す','ガロは箱を受け取り、盗難で金が失われたという説明を続けた。あなたは台帳を確認していない。疑われた荷役人への疑いは解けなかった。',and(s.is('boxAt','garo'),s.is('report'),not(s.is('witnessed'))));
 s.end('compromise','証拠を荷役人へ引き渡す','荷役人は箱・台帳・目撃報告を受け取り、自分たちで支払い交渉を始めた。不正の説明を追及する材料はあるが、実際の支払いはまだ確認していない。',and(s.is('delegated'),s.is('boxAt','workers'),s.is('ledgerAt','workers'),s.is('ledgerRead')));
 rows.push(s.done());
}
{
 const s=story(7,{port:'地下室の伝声口',corridor:'保守通路',booth:'廃番所の伝声室'},[['port','corridor'],['corridor','booth']]);
 s.entity('mire','port','mire').entity('brother','booth','brother').entity('letters','brother').entity('pipe','port');
 for(const k of ['voiceKnown','mireConsent','brotherConsent','lettersConsent','sealed','met','delivered'])s.bool(k);
 s.bool('pipeOpen',true);s.fact('voice','夫の声をまねていたのは、その弟').fact('letters','弟は故人の手紙を預かっていた');
 s.past=['ミレの夫は亡くなっている。弟が保守通路の先の伝声室から声をまねた。手紙は弟が保持しており、管の向こうへ人が通れるわけではない。'];s.progression='声での応答と対面を区別する。手紙は弟から預かって通路を運び、面会は双方の同意がそろって初めて実行する。';
 s.node('entry','port',['mire'],'壁の伝声口から、亡くなった夫の声がした。ミレは返事を待っている。横の点検札には、保守通路が廃番所へ続くと書かれていた。',[O('reply','故人だけが知る言い回しを、ミレに尋ねて返す','voice',[see('voice','pipe',s.is('pipeOpen')),set('voiceKnown')]),O('trace','ミレにここで待ってもらい、保守通路をたどる','booth',[move('party','port','corridor','booth'),see('voice','brother'),see('letters','letters'),set('voiceKnown')]),O('seal','声を聞き続けるか尋ね、ミレの同意を得て伝声口を塞ぐ','@contract',[set('mireConsent'),set('pipeOpen',false),set('sealed')])]);
 s.node('voice','port',['mire',{entity:'brother',mode:'remote',requires:s.is('pipeOpen')}],'返事が詰まった。「兄貴の手紙を、渡せなくて」。弟は向こうの伝声室にいると名乗った。ミレは会う前に、手紙を読みたいと言った。',[O('walk','ミレを待たせ、保守通路から弟を訪ねる','booth',[move('party','port','corridor','booth'),see('letters','letters')]),O('seal','ミレの意思を確かめ、この声のやり取りを終える','@contract',[set('mireConsent'),set('pipeOpen',false),set('sealed')])]);
 s.node('booth','booth',['brother'],'弟は手紙の束を机へ出した。「真似をしていれば、渡さなくても許される気がした」。手紙を届けることには同意した。面会の意思は、二人に別々に聞かなければならない。',[O('letters','差出人と預かり人を確認し、手紙を預かってミレへ戻る','letters',[set('lettersConsent'),give('letters','brother','party'),move('party','booth','corridor','port'),give('letters','party','mire'),set('delivered')])]);
 s.node('letters','port',['mire',{entity:'brother',mode:'remote',requires:s.is('pipeOpen')}],'ミレは夫の手紙を読み、弟が預かっていたと確かめた。管越しに弟へ「自分の声で話して」と言う。あなたは、顔を合わせたいかを尋ねた。',[O('meet','双方の面会への同意を確かめ、弟を迎えに行く','meeting',[set('mireConsent'),set('brotherConsent'),move('party','port','corridor','booth'),move('party brother','booth','corridor','port'),set('met')]),O('finish','手紙の受け渡しで区切り、面会は強いない','@compromise')]);
 s.node('meeting','port',['mire','brother'],'弟は伝声口の外で、初めて自分の声で謝った。ミレは手紙を閉じた。「返事を決めるのは、私にさせて」。',[O('finish','二人の面会を見届け、その場を離れる','@informed')]);
 s.end('informed','手紙を渡し、同意した二人を会わせる','ミレは夫の手紙を受け取り、弟は保守通路を歩いて彼女の前へ出た。互いに望んだ面会は成立したが、許しや今後の関係までは決まっていない。',and(s.is('delivered'),s.is('met'),s.is('mireConsent'),s.is('brotherConsent'),s.is('brotherAt','port')));
 s.end('contract','同意を得て伝声口を塞ぐ','ミレが望んで伝声口を塞いだ。声は止まった。弟と手紙は廃番所に残り、手紙を受け取ったことにも、二人が会ったことにもならない。',and(s.is('sealed'),not(s.is('pipeOpen')),s.is('mireConsent'),s.is('lettersAt','brother')));
 s.end('compromise','手紙だけを届ける','弟から預かった手紙をミレへ届け、誰が預かっていたかも伝えた。弟は廃番所に残った。二人の対面は成立させず、返事を決める時間をミレに渡した。',and(s.is('delivered'),s.is('lettersAt','mire'),s.is('brotherAt','booth'),not(s.is('met'))));
 rows.push(s.done());
}
{
 const s=story(8,{shore:'水葬場の岸',threshold:'浅瀬の段差',jetty:'下流の受取桟橋',office:'検査窓口',mortuary:'待棺所',river:'水葬の流れ'},[['shore','threshold'],['threshold','jetty'],['shore','office'],['shore','mortuary'],['jetty','river'],['shore','river']]);
 s.entity('yoru','shore','yoru').entity('family','shore','family',{kind:'group'}).entity('bearers','shore','bearers',{kind:'group'}).entity('recipient','jetty','recipient').entity('inspector','office','inspector').entity('coffin','threshold').entity('body','coffin').entity('food','coffin');
 for(const k of ['consent','inspected','permit','delivered','funeral','postponed','declared'])s.bool(k);
 s.fact('cargo','棺の外底には食料の包みが隠されている');
 s.past=['ヨルは通行税を避けて食料を届けるため、遺体の内室と別の外底へ食料を詰めた。棺は重くなり、浅瀬の段差を越えられない。'];s.progression='遺体・棺・食料を別の実体として追う。棺を流す行為と食料の輸送許可を一度の出来事にしない。';
 s.node('entry','shore',['yoru','family','bearers'],'棺は沈み切らず、段差に腹を掛けている。ヨルが綱を引くと、遺族も持ち上げようとした。下流には受取桟橋がある。',[O('inspect','遺族の了承を得て岸へ引き戻し、遺体に触れず外底を調べる','cargo',[set('consent'),move('party bearers','shore','threshold'),give('coffin','threshold','party'),move('party bearers','threshold','shore'),give('coffin','party','shore'),set('inspected'),see('cargo','food')]),O('tow','水辺の魔物を退け、棺を段差の向こうへ曳く','@contract',[move('party bearers','shore','threshold'),give('coffin','threshold','party'),move('party bearers','threshold','jetty'),give('food','coffin','recipient'),set('delivered'),move('party bearers','jetty','river'),give('coffin','party','river'),set('funeral')],{combat:true})]);
 s.node('cargo','shore',['yoru','family','bearers'],'外底から食料の包みが出た。遺体は内室に安置されたままだ。ヨルは、下流の人へ税を払えず届けられなかったと認めた。',[O('declare','食料を分け、遺族の水葬を終えてから輸送許可を申請する','application',[give('food','coffin','yoru'),give('coffin','shore','party'),move('party family bearers','shore','river'),give('coffin','party','river'),set('funeral'),move('party family bearers','river','shore'),move('party yoru','shore','office'),set('declared')]),O('quiet','遺族に事情を伝えて棺を待棺所へ移し、受取人を呼びに行く','postponed',[give('coffin','shore','party'),move('party family bearers','shore','mortuary'),give('coffin','party','mortuary'),set('postponed'),move('party','mortuary','shore','threshold','jetty'),move('party recipient','jetty','threshold','shore')])]);
 s.node('application','office',['yoru','inspector'],'検査官は今回の包みの量と行先を記録した。恒久的な免税ではなく、この便の臨時許可を審査する。受取人にも照会を取りに行く必要がある。',[O('permit','受取人を窓口へ案内し、確認と許可を得てから食料を運ぶ','@informed',[move('party','office','shore','threshold','jetty'),move('party recipient','jetty','threshold','shore','office'),set('permit'),move('party recipient yoru','office','shore','threshold','jetty'),give('food','yoru','recipient'),set('delivered')])]);
 s.node('postponed','shore',['yoru','recipient'],'受取人を桟橋から連れてきた。遺族は待棺所で待っている。食料を外せば棺は軽くなるが、葬儀を再開する時刻はまだ決めていない。',[O('deliver','受取人と待棺所へ行き、食料だけ外して桟橋へ届ける','@compromise',[move('party recipient yoru','shore','mortuary'),give('food','coffin','recipient'),move('party recipient yoru','mortuary','shore','threshold','jetty'),set('delivered')])]);
 s.end('informed','水葬と許可された食料輸送','遺体を納めた棺は水葬の流れへ送り出した。食料は外底から分け、受取人の照会を経た今回限りの許可で桟橋へ届けた。恒久的な輸送制度の見直しは申請として残る。',and(s.is('funeral'),s.is('permit'),s.is('delivered'),s.is('bodyAt','coffin'),s.is('foodAt','recipient')));
 s.end('contract','重い棺を下流へ曳く','棺を段差の先へ曳いた。下流の受取人は外底の荷を外し、棺は水葬の流れへ送られた。荷の由来を調べないまま、棺に食料を隠す輸送は続く。',and(s.is('funeral'),s.is('delivered'),not(s.is('inspected')),s.is('coffinAt','river')));
 s.end('compromise','水葬を延期して食料を届ける','棺と遺体は遺族の了承のもと待棺所に残し、食料だけを受取人へ届けた。飢えへの手当てはできたが、水葬は未完了で、輸送許可も得ていない。',and(s.is('postponed'),s.is('coffinAt','mortuary'),s.is('delivered'),not(s.is('funeral'))));
 rows.push(s.done());
}
{
 const s=story(9,{junction:'鼠の集まる分岐',work:'清掃区画',granary:'穀倉の外室',store:'共同倉庫'},[['junction','work'],['junction','granary'],['granary','store']]);
 s.entity('eda','junction','eda').entity('cleaners','work','cleaners',{kind:'group'}).entity('storekeeper','granary','storekeeper').entity('clerks','store','clerks',{kind:'group'}).entity('rats','granary',null,{kind:'group'}).entity('grain','granary').entity('plans','eda').entity('pillars','junction');
 for(const k of ['structureChecked','causeKnown','zones','holes','verified','hunted','received'])s.bool(k);
 s.fact('structure','この区画の支柱には新しい変位が見られない').fact('cause','清掃薬で餌場を失った鼠が穀倉へ向かっている');
 s.past=['清掃範囲が一度に広がり、鼠は餌を失って穀倉へ移った。穀倉番が内扉を閉めており、穀物のある室内へはまだ入っていない。'];s.progression='崩落の確認、清掃の区分、侵入口封鎖、穀物移送を独立した状態として残す。作業順を変えても、済んだ作業を取り消さない。';
 s.node('entry','junction',['eda'],'エダは鼠の流れを見て「崩れる前触れか」と尋ねた。穀倉番からは、内扉を閉じて持ちこたえていると連絡が来ている。',[O('trace','旧図と支柱を比較し、白い粉の跡を清掃区画へ追う','work',[see('structure','pillars'),set('structureChecked'),move('party','junction','work'),see('cause','cleaners'),set('causeKnown')]),O('hunt','穀倉の外室で群れを追い払い、侵入が止まったか確認する','@contract',[move('party','junction','granary'),move('rats','granary','junction','work'),set('hunted')],{combat:true}),O('move','穀倉へ行き、共同倉庫への避難搬送を手配する','granary',[move('party','junction','granary')])]);
 s.node('work','work',['cleaners'],when(s.is('zones'),'清掃係は合意した区画表を保持している。すでに撒いた薬は取り消せない。次回からの範囲と、残す餌場を区切った。','清掃係は白い薬の袋を見せた。「全部きれいにするように、と」。鼠を追い出した先は穀倉だった。'),[O('zones','清掃係と次回以降の区画分けを合意する','work',[set('zones')],{when:not(s.is('zones'))}),O('granary','穀倉の侵入口を確かめに行く','granary',[move('party','work','junction','granary')],{once:false})]);
 s.node('granary','granary',['storekeeper'],[when(s.is('holes'),'外室への穴は塞いである。内扉は引き続き閉めている。','鼠はまだ外室にいる。穀倉番は内扉を押さえ、穀物との間を守っている。'),when(s.is('zones'),'清掃の区画分けは合意済みだ。','清掃範囲の合意はまだ取っていない。')],[O('holes','外室の鼠を誘導してから侵入口を塞ぐ','granary',[move('rats','granary','junction','work'),set('holes')],{when:not(s.is('holes'))}),O('work','清掃係へ行き、区画分けを詰める','work',[move('party','granary','junction','work'),see('cause','cleaners'),set('causeKnown')],{once:false}),O('verify','支柱の比較と薬・鼠の動線を再点検して、二つの対策を確認する','@informed',[move('party','granary','junction'),see('structure','pillars'),set('structureChecked'),move('party','junction','work'),see('cause','cleaners'),set('causeKnown'),set('verified')],{when:and(s.is('zones'),s.is('holes')),requirement:'清掃の区画分け・侵入口の封鎖'}),O('grain','共同倉庫の受入れを確認し、穀物を運び込む','@compromise',[move('party','granary','store'),move('party clerks','store','granary'),give('grain','granary','party'),move('party clerks','granary','store'),give('grain','party','clerks'),set('received')])]);
 s.end('informed','清掃範囲と鼠の入口を分ける','この区画の支柱に新しい変位がないことを確認し、清掃で餌場を失った鼠の流れを突き止めた。次回からの清掃範囲を分け、穀倉の侵入口を塞いだ。当地の崩落警戒は解除したが、他区画の安全までは断定しない。',and(s.is('structureChecked'),s.is('causeKnown'),s.is('zones'),s.is('holes'),s.is('verified')));
 s.end('contract','穀倉前の群れを追い払う','外室の群れを追い払い、内扉の向こうの穀物を守った。鼠を追い出した清掃の運用は変わらず、構造物の安全も調べていない。群れが戻る可能性は残る。',s.is('hunted'));
 s.end('compromise','穀物を共同倉庫へ移す','受入れ係と数量を照合して、穀物を共同倉庫へ運び込んだ。共同の入出庫帳で、誰に配られたかが見えるようになった。すでに合意した清掃区分や封鎖作業は維持されるが、未実施の対策を済ませたことにはしない。',and(s.is('received'),s.is('grainAt','clerks')));
 rows.push(s.done());
}
{
 const s=story(10,{control:'高所の水門操作室',near:'手前の避難通路',deep:'奥の作業区画',shaft:'封鎖された縦坑',ground:'地上の救助口',landing:'帳簿のある踊り場'},[['control','near'],['near','deep'],['control','shaft'],['shaft','ground'],['near','landing']]);
 s.entity('keeper','control','gatekeeper').entity('rine','ground','rine').entity('nearPeople','near','nearpeople',{kind:'group'}).entity('deepPeople','deep','deeppeople',{kind:'group'}).entity('crew','ground','pumpcrew',{kind:'group'}).entity('book','landing').entity('rescueRope','keeper');
 for(const k of ['shaftChecked','ropeRigged','nearSaved','deepSaved','bookSaved','closed','pumpHandover','testimony','filed'])s.bool(k);
 s.fact('delay','門番は命令を待つ間に避難用の縦坑を準備していた').fact('book','補強工事の台帳には契約印が欠けている');
 s.past=['門番は補強工事が未承認と知りながら閉門の命令を待ち、住民の逃げ口を準備した。手前に三人、奥に二人いる。縦坑は避難に使えるが、封鎖を解いて両端を検査するまで通さない。'];s.progression='住民三人・二人の地上到着、帳簿回収、門番の証言を別々に確認する。閉門は不可逆で、残留者の人数を表示してから選ぶ。';
 s.node('entry','control',['keeper'],'門番は閉門綱を握っている。「手前に三人、奥に二人。閉めれば、こちらからは戻れん」。横には準備した救助縄と、封鎖札の付いた縦坑がある。',[O('shaft','封鎖を解き、縦坑の両端を検査してリネと連絡を取る','operations',[move('party','control','shaft','ground'),move('party','ground','shaft','control'),set('shaftChecked'),see('delay','keeper')]),O('close','五人が残ることを確認し、住民救助を断念して閉門する','@contract',[move('party','control','shaft','ground'),set('shaftChecked'),move('party','ground','shaft','control'),set('closed'),move('party keeper','control','shaft','ground')],{requirement:'住民五人が内側に残る。閉門後は戻れない'}),O('pump','縦坑を検査し、地上の排水隊へ現場を引き継ぐ','@compromise',[move('party','control','shaft','ground'),set('shaftChecked'),move('party crew','ground','shaft','control'),set('pumpHandover'),move('party keeper','control','shaft','ground')])]);
 const finish=[set('closed'),move('party keeper','control','shaft','ground')];
 s.node('operations','control',['keeper'],['縦坑の両端を確認した。リネは地上で到着人数を記録する。作業の順番は選べる。救助縄は奥の渡りに固定し、撤収まで残す。',when(s.is('nearSaved'),'手前の三人は地上に到着済み。','手前の三人はまだ通路にいる。'),when(s.is('deepSaved'),'奥の二人は地上に到着済み。','奥の二人はまだ作業区画にいる。'),when(s.is('bookSaved'),'帳簿は地上のリネが預かっている。','帳簿は踊り場に残っている。')],[O('near','手前の三人を縦坑から地上へ送り、到着を確認する','operations',[move('party','control','near'),move('party nearPeople','near','control','shaft','ground'),set('nearSaved'),move('party','ground','shaft','control')],{when:not(s.is('nearSaved'))}),O('deep','救助縄を張り、奥の二人を地上へ送って到着を確認する','operations',[give('rescueRope','keeper','party'),move('party','control','near'),give('rescueRope','party','near'),set('ropeRigged'),move('party','near','deep'),move('party deepPeople','deep','near','control','shaft','ground'),set('deepSaved'),move('party','ground','shaft','control')],{when:not(s.is('deepSaved'))}),O('book','踊り場の帳簿を回収し、地上のリネへ預ける','operations',[move('party','control','near','landing'),give('book','landing','party'),see('book','book'),move('party','landing','near','control','shaft','ground'),give('book','party','rine'),set('bookSaved'),move('party','ground','shaft','control')],{when:not(s.is('bookSaved'))}),O('all','五人の到着を照合し、縄を回収して門番と閉門する','ground',[move('party','control','near'),give('rescueRope','near','party'),move('party','near','control'),set('ropeRigged',false),...finish],{when:and(s.is('nearSaved'),s.is('deepSaved')),requirement:'手前三人・奥二人の地上到着'}),O('partial','救助できた組だけを確定し、残る組を断念して閉門する','@partial',finish,{when:or(and(s.is('nearSaved'),not(s.is('deepSaved'))),and(s.is('deepSaved'),not(s.is('nearSaved')))),requirement:'表示中の未救助者が内側に残る。閉門後は戻れない'}),O('close','まだ五人が残る状態で閉門する','@contract',finish,{when:and(not(s.is('nearSaved')),not(s.is('deepSaved'))),requirement:'住民五人が内側に残る'}),O('pump','現在の救助数と証拠の所在を伝え、到着した排水隊に引き継ぐ','@compromise',[move('party','control','shaft','ground'),move('party crew','ground','shaft','control'),set('pumpHandover'),move('party keeper','control','shaft','ground')])]);
 s.node('ground','ground',['keeper','rine','nearPeople','deepPeople'],'リネの名簿で住民五人の到着を照合した。門番も地上へ出て、水門は閉じた。ここからは救助の成否ではなく、何を記録に残すかを選ぶ。',[O('testimony','帳簿と門番本人の証言を、リネの報告に載せる','@informed',[set('testimony'),set('filed')],{when:s.is('bookSaved'),requirement:'帳簿がリネの手元にある'}),O('rescue','全員の救助報告で区切る','@rescued')]);
 const all=and(s.is('nearSaved'),s.is('deepSaved'),s.is('nearPeopleAt','ground'),s.is('deepPeopleAt','ground'),s.is('keeperAt','ground'),s.is('closed'));
 s.end('informed','全員を救い、工事の記録と証言を残す','住民五人と門番が地上へ帰った。帳簿と本人の証言がリネの報告に載り、契約印を欠いた補強工事と閉門の遅れを調べる根拠になった。責任の裁定は、救助の後に残された。',and(all,s.is('bookAt','rine'),s.is('testimony'),s.is('filed')));
 s.end('rescued','全員の救助を完了する','住民五人と門番は地上へ出て、水門を閉じた。救助の成功を報告した。回収済みの帳簿があればリネの手元に残るが、帳簿と門番の証言をそろえた調査報告は作っていない。',all);
 s.end('partial','救助済みの組を確定して閉門','到着済みの組だけを救助名簿へ記し、門番と閉門した。操作室で最後に表示した未救助の組は内側に残った。閉門後に救い出したことにはならず、生死は確認できていない。',and(s.is('closed'),or(and(s.is('nearSaved'),not(s.is('deepSaved'))),and(s.is('deepSaved'),not(s.is('nearSaved'))))));
 s.end('contract','住民を救う前に閉門','住民五人が内側に残ると確認した上で、門番と閉門して地上へ出た。地上への流入は止まったが、五人の帰還は確認されていない。',and(s.is('closed'),not(s.is('nearSaved')),not(s.is('deepSaved'))));
 s.end('compromise','到着した排水隊へ引き継ぐ','排水隊が操作室に到着し、現在の救助数と帳簿の所在を引き継いだ。門番は地上へ出た。すでに救った住民は地上に残り、未救助者の帰還を先取りして報告しなかった。',and(s.is('pumpHandover'),s.is('crewAt','control'),s.is('keeperAt','ground'),not(s.is('closed'))));
 s.invariant('near_arrival',{op:'eq',left:s.v('nearSaved'),right:s.is('nearPeopleAt','ground')},'到着人数は実際の所在と一致する');
 s.invariant('deep_arrival',{op:'eq',left:s.v('deepSaved'),right:s.is('deepPeopleAt','ground')},'到着人数は実際の所在と一致する');
 rows.push(s.done());
}
export default rows;
