import {story,O,move,give,set,see,when,and,or,not} from './story-kit.mjs';
import previousQ008Story from './compat/q008-story-v1.json' with {type:'json'};
const rows=[];
{
 const s=story(6,{landing:'水路の回収場',water:'箱が沈む浅瀬',shore:'荷役人の待機岸',office:'ガロの事務所'},[['landing','water'],['landing','shore'],['shore','office']]);
 s.entity('garo','landing','garo').entity('workers','shore','workers',{kind:'group'}).entity('accused','shore','accused').entity('box','water').entity('ledger','office').entity('stones','box');
 s.story.registry.ledgerAt.meaning='給金台帳と入金台帳を一組で保持する所在';
 for(const k of ['opened','witnessed','ledgerRead','handed','partialPaid','delegated','report'])s.bool(k);
 s.fact('stones','給金箱に金ではなく石が入っていた').fact('wages','給金台帳には職人ごとの未払額がある').fact('deposits','入金台帳には給金箱へ現金を入れた記録がない').fact('debt','石入りの箱と給金台帳・入金台帳を照合し、盗難ではなく最初から未払いだったと分かった');
 s.brief="職人の給金を入れた箱が水路へ沈み、最後に箱を運んだ荷役人が疑われています。箱を回収してください。";
 s.past=["工事費を使い切ったガロには、職人へ払う給金が残っていなかった。ガロは空の給金箱へ石を詰め、最後に箱を扱った荷役人の作業場所近くへ沈め、運搬中の盗難に見せかけた。職人たちから第三者による捜索を求められたため、ガロは箱を開けず自分へ返す条件で冒険者へ回収を依頼した。"];
 s.authoringNotes={"notice":"以下の事実はq006を成立させる世界設定上の制約です。これらを台詞、説明、選択肢としてシナリオへ直接反映する必要はありません。ただし、生成・改稿時に矛盾させてはいけません。","factsHeading":"世界設定上の事実","facts":["給金箱は施錠されており、回収者は依頼人へ未開封で返すのが通常です。ガロはこの慣行を利用し、石入りの箱を私的に回収して処分するつもりです。","疑われた荷役人は最後に空箱を所定位置まで運びましたが、給金を受け取っておらず、箱を沈めてもいません。","事務所の給金台帳には職人ごとの未払額があり、入金台帳には給金箱へ現金を入れた記録がありません。石入りの箱と二つの台帳を公開の場で照合すれば、盗難ではなく最初から未払いだったと立証できます。"]};
 s.revealText=s.past.join(' ');s.progression="箱を私的に返すと中身を隠せる。公開の場で箱を開き、給金台帳と入金台帳を照合した場合だけ、盗難ではなく未払いの偽装だったと確定する。";
 s.node('entry','landing',['garo'],'「鍵は私が持つ。開けずに返してくれ」。ガロが施錠された給金箱の沈没位置を指した。岸では職人たちが第三者による捜索を求めている。最後に空箱を運んだ荷役人へ、疑いの目が集まっていた。',[O('lift',"縄で箱を引き上げ、水路の魔物を退ける",'box',[move('party','landing','water'),give('box','water','party'),move('party','water','landing')],{cost:{rope:1},combat:true}),O('witness',"荷役人に沈没位置を伝え、彼らの道具で一緒に回収する",'accounts',[move('party','landing','shore'),move('party workers accused','shore','landing','water'),give('box','water','party'),move('party workers accused','water','landing','shore'),set('opened'),set('witnessed'),see('stones','stones')])]);
 s.node('box','landing',['garo'],'引き揚げた箱には鍵が掛かったままだ。中身はまだ確かめていない。ガロが受け取ろうと手を伸ばす。「依頼は回収だ。中は私が確認する」。',[O('return',"箱を未開封のままガロへ返す",'private',[give('box','party','garo'),set('handed')]),O('public',"箱を保持し、荷役人の前で開く",'accounts',[move('party','landing','shore'),set('opened'),see('stones','stones'),set('witnessed')])]);
 s.node('private','landing',['garo'],'未開封の箱はガロの足元にある。岸から「中身を見せてくれ」と声が届いた。ガロは箱を抱え直した。ここで立ち去れば、中身を確かめる機会は失われる。',[O('leave',"未開封で返した仕事として報告を終える",'@contract',[set('report')]),O('retract',"報告を保留し、箱を返してもらって荷役人の前へ運ぶ",'accounts',[give('box','garo','party'),set('handed',false),move('party','landing','shore'),set('opened'),see('stones','stones'),set('witnessed')])]);
 s.node('accounts','shore',['workers','accused'],'荷役人たちの前で箱を開けると、金の代わりに石が出た。「俺が運んだ時は空だった」。疑われた荷役人が言う。石だけでは、金が盗まれたのか、最初から入っていなかったのかは決まらない。事務所の給金台帳と入金台帳を確かめる必要がある。',[O('ledger',"箱の石を確認し、ガロに同行を求めて事務所の二つの台帳を確かめる",'ledger',[move('party','shore','landing'),move('party garo','landing','shore'),move('party garo workers accused','shore','office'),see('wages','ledger'),see('deposits','ledger'),see('debt','ledger',and(s.known('stones'),s.known('wages'),s.known('deposits'))),give('ledger','office','party'),set('ledgerRead'),move('party garo workers accused','office','shore')])]);
 s.node('ledger','shore',['garo','workers','accused'],'給金台帳には未払額が並び、入金台帳には箱へ現金を入れた記録がない。石入りの箱と合わせると、盗難という説明は成り立たなかった。ガロは口をつぐんでいる。箱と二つの台帳は、あなたが保持している。',[O('settle',"ガロの私物売却による一部払いを全員の前で成立させる",'@informed',[set('partialPaid'),give('box','party','workers'),give('ledger','party','workers'),set('report')]),O('delegate',"箱と二つの台帳と目撃報告を荷役人へ渡し、交渉を委ねる",'@compromise',[give('box','party','workers'),give('ledger','party','workers'),set('delegated'),set('report')])]);
 s.end('informed',"台帳を開き一部払いを成立させる","石入りの箱、給金台帳、入金台帳を職人全員の前で照合し、ガロは盗難の説明を撤回した。ガロは自分の荷車と予備工具を売って給金の一部を払った。荷役人への疑いは解けたが、残額と工事の停止が残る。",and(s.is('witnessed'),s.is('ledgerRead'),s.is('partialPaid'),s.is('report')));
 s.end('contract',"給金箱を私的に返す","未開封の箱を受け取ったガロは、盗難で給金が失われたという説明を続けた。箱の中身も入金台帳も公開されず、疑われた荷役人への疑いは解けなかった。",and(s.is('boxAt','garo'),s.is('report'),not(s.is('witnessed'))));
 s.end('compromise',"証拠を荷役人へ引き渡す","荷役人は石入りの箱、給金台帳、入金台帳、沈没位置の目撃報告を受け取り、自分たちで支払い交渉を始めた。不正を追及する材料は渡ったが、ガロによる説明の撤回と実際の支払いまでは確認していない。",and(s.is('delegated'),s.is('boxAt','workers'),s.is('ledgerAt','workers'),s.is('ledgerRead')));
 rows.push(s.done());
}
{
 const s=story(7,{port:'地下室の伝声口',corridor:'保守通路',booth:'廃番所の伝声室'},[['port','corridor'],['corridor','booth']]);
 s.entity('mire','port','mire').entity('brother','booth','brother').entity('letters','brother').entity('pipe','port');
 for(const k of ['voiceKnown','mireConsent','brotherConsent','lettersConsent','sealed','met','delivered'])s.bool(k);
 s.bool('pipeOpen',true);s.fact('unanswered','声は故人だけが知る出来事への問いに答えなかった');s.fact('voice','夫の声をまねていたのは、その弟').fact('letters','弟は故人の手紙を預かっていた');
 s.brief="地下の壁から亡夫の声が聞こえると噂されています。声の主を確かめてください。";
 s.past=["ミレの夫は亡くなっている。遺品を整理した夫の弟は、兄が渡せなかった手紙を見つけたが、自分が届ければミレに拒まれることを恐れた。弟は廃番所の伝声室から手紙を読み、兄に似た自分の声を故人の話し方へ寄せて、壁越しにミレへ聞かせていた。"];
 s.authoringNotes={"notice":"以下の事実はq007を成立させる世界設定上の制約です。これらを台詞、説明、選択肢としてシナリオへ直接反映する必要はありません。ただし、生成・改稿時に矛盾させてはいけません。","factsHeading":"世界設定上の事実","facts":["酒場の壁と廃番所は、かつて地下警備に使われた伝声管でつながっています。管は音だけを運び、人が通れる大きさではありません。廃番所へは別の保守通路から到達できます。","兄弟は声質が似ており、伝声管による反響と歪みが違いを分かりにくくしています。弟は兄の手紙を読んでいるため内容の一部を知っていますが、手紙にない問いへ故人として正確に答えることはできません。","手紙は夫が生前に書いた原本で、弟が保持しています。声の応答、手紙の受け渡し、弟との対面は、それぞれ別の出来事です。"]};
 s.revealText=s.past.join(' ');s.progression="手紙にない問いへの返答を手掛かりに、声の主を調べる。保守通路で弟と手紙を見つけた後も、手紙の受け渡しと双方の同意を得た面会を分ける。";
 s.node('entry','port',['mire'],'壁の伝声口から、亡くなった夫の声がした。ミレは返事を待っている。横の点検札には、保守通路が廃番所へ続くと書かれていた。',[O('reply',"故人だけが知る出来事をミレに尋ね、その問いを壁へ返す",'voice',[see('unanswered','pipe',s.is('pipeOpen'))]),O('trace',"ミレにここで待ってもらい、保守通路をたどる",'booth',[move('party','port','corridor','booth'),see('voice','brother'),see('letters','letters'),set('voiceKnown')]),O('seal',"声を聞き続けるかミレへ尋ね、本人の同意を得て伝声口を塞ぐ",'@contract',[set('mireConsent'),set('pipeOpen',false),set('sealed')])]);
 s.node('voice','port',['mire'],'ミレが教えた出来事を問うと、壁の向こうは黙った。しばらくして、先ほどと同じ言葉を読み直すような声がした。「あの話を、あの人が忘れるはずないのに」。ミレは伝声口を見つめている。',[O('walk',"問いへの返答を手掛かりに、保守通路から声の主を訪ねる",'booth',[move('party','port','corridor','booth'),see('voice','brother'),see('letters','letters'),set('voiceKnown')]),O('seal',"ミレの意思を確かめ、この声のやり取りを終える",'@contract',[set('mireConsent'),set('pipeOpen',false),set('sealed')])]);
 s.node('booth','booth',['brother'],'伝声室で夫の弟が手紙を握っていた。「遺品から見つけたんです。僕が届けても、受け取ってもらえないと思って」。兄に似た声で原本を読んでいたと認めた。手紙を届けることには同意したが、会うかどうかはミレにも確かめる必要がある。',[O('letters',"弟が声の主であることと手紙の差出人を確認し、原本を預かってミレへ戻る",'letters',[set('lettersConsent'),give('letters','brother','party'),move('party','booth','corridor','port'),give('letters','party','mire'),set('delivered')])]);
 s.node('letters','port',['mire',{entity:'brother',mode:'remote',requires:s.is('pipeOpen')}],'ミレは夫の筆跡を確かめ、手紙を読み終えた。弟が壁の向こうで読んでいたと伝えると、管へ向かって「今度は、自分の言葉で話して」と言った。返事が届いても、二人が会うと決まったわけではない。',[O('meet',"ミレと弟の双方に面会の意思を確かめ、弟を迎えに行く",'meeting',[set('mireConsent'),set('brotherConsent'),move('party','port','corridor','booth'),move('party brother','booth','corridor','port'),set('met')]),O('finish',"手紙の受け渡しで区切り、面会は強いない",'@compromise')]);
 s.node('meeting','port',['mire','brother'],'弟は伝声口の外で、初めて自分の声で謝った。ミレは手紙を閉じた。「返事を決めるのは、私にさせて」。',[O('finish',"二人の面会を見届け、その場を離れる",'@informed')]);
 s.end('informed',"手紙を渡し、同意した二人を会わせる","ミレは夫の手紙を受け取り、弟は保守通路を歩いて彼女の前へ出た。双方が望んだ面会は成立したが、弟の行為を許すか、今後も関係を続けるかまでは決まっていない。",and(s.is('delivered'),s.is('met'),s.is('mireConsent'),s.is('brotherConsent'),s.is('brotherAt','port')));
 s.end('contract',"同意を得て伝声口を塞ぐ","ミレが声を聞かないことを選び、伝声口を塞いだ。声は止まった。弟と手紙は廃番所に残り、手紙の受け渡しも二人の対面も成立していない。",and(s.is('sealed'),not(s.is('pipeOpen')),s.is('mireConsent'),s.is('lettersAt','brother')));
 s.end('compromise',"手紙だけを届ける","弟から夫の手紙を預かってミレへ届け、弟が声の主だったことも伝えた。弟は廃番所に残った。対面を強いず、返事を決める時間をミレに渡した。",and(s.is('delivered'),s.is('lettersAt','mire'),s.is('brotherAt','booth'),not(s.is('met'))));
 rows.push(s.done());
}
{
 const s=story(8,{shore:'水葬場の岸',threshold:'浅瀬の段差',jetty:'下流の受取桟橋',office:'検査窓口',mortuary:'待棺所',river:'水葬の流れ'},[['shore','threshold'],['threshold','jetty'],['shore','office'],['shore','mortuary'],['jetty','river'],['shore','river']]);
 s.entity('yoru','shore','yoru').entity('family','shore','family',{kind:'group'}).entity('bearers','shore','bearers',{kind:'group'}).entity('recipient','jetty','recipient').entity('inspector','office','inspector').entity('coffin','threshold').entity('body','coffin').entity('outerBase','coffin').entity('food','outerBase');
 s.story.registry.coffinAt.meaning='遺体を封じた内室の所在・保持者。外底は別に管理する';
 s.story.registry.outerBaseAt.meaning='浮力を調整する外底の所在・保持者';
 s.story.registry.foodAt.meaning='外底に隠した食料の所在・保持者';
 s.story.revision=2;
 s.storyUpgrades=[{fromRevision:1,toRevision:2,previous:previousQ008Story,values:[
  {key:'outerBaseAt',value:'coffin'},
  {key:'outerBaseAt',value:'shore',when:s.is('funeral')},
  {key:'outerBaseAt',value:'jetty',when:{op:'contains',left:{ref:'stories.q008.events'},right:'entry_tow'}},
  {key:'foodAt',value:'outerBase',when:s.is('foodAt','coffin')}
 ]}];
 for(const k of ['consent','inspected','permit','delivered','funeral','postponed','declared'])s.bool(k);
 s.fact('cargo','棺の外底には食料の包みが隠されている');
 s.brief="水葬用の棺が浅瀬に引っ掛かり、葬列が止まっています。棺を流れへ戻し、葬儀を終えてください。";
 s.past=["下流集落へ食料を届けようとしたヨルは、貨物の通行税と検査を避けるため、水葬用の棺の外底へ食料を隠した。食料は封じた遺体の内室とは接していない。重量と喫水が設計値を超えた棺は浅瀬の段差に乗り上げ、葬列を止めた。"];
 s.authoringNotes={"notice":"以下の事実はq008を成立させる世界設定上の制約です。これらを台詞、説明、選択肢としてシナリオへ直接反映する必要はありません。ただし、生成・改稿時に矛盾させてはいけません。","factsHeading":"世界設定上の事実","facts":["この地域の水葬では、遺体を封じた棺を指定水路へ流し、下流の葬送桟橋を経て町外へ送り出します。水葬用の棺は葬送組合が管理し、通常の貨物検査と通行税を免除されています。","棺には遺体を封じる内室と、浮力を調整する外底があります。ヨルは外底へ食料を詰めたため、食料は遺体へ触れていませんが、棺は本来の浮力を失っています。","下流の受取人は葬送桟橋で外底だけを外し、食料を受け取る予定でした。棺の内室は開けず、そのまま水葬経路へ戻す手筈です。"]};
 s.revealText=s.past.join(' ');s.progression="遺体を封じた内室、棺の外底、隠された食料を別の実体として扱う。遺族の了承、水葬の実施、食料の受取人確認、輸送許可を一度の出来事にまとめない。";
 s.node('entry','shore',['yoru','family','bearers'],'棺は沈み切らず、段差に腹を掛けている。ヨルが綱を引くと、遺族も持ち上げようとした。下流には受取桟橋がある。',[O('inspect',"遺族の了承を得て棺を岸へ引き戻し、内室を開けず外底を調べる",'cargo',[set('consent'),move('party bearers','shore','threshold'),give('coffin','threshold','party'),move('party bearers','threshold','shore'),give('coffin','party','shore'),set('inspected'),see('cargo','food')]),O('tow',"水辺の魔物を退け、重い棺を段差の向こうへ曳く",'@contract',[move('party bearers','shore','threshold'),give('coffin','threshold','party'),move('party bearers','threshold','jetty'),give('outerBase','coffin','jetty'),give('food','outerBase','recipient'),set('delivered'),move('party bearers','jetty','river'),give('coffin','party','river'),set('funeral')],{combat:true})]);
 s.node('cargo','shore',['yoru','family','bearers'],'外底の点検口を開くと食料の包みが見えた。遺体を封じた内室には触れていない。ヨルは、葬送用の棺が貨物検査と通行税を免除されるため、下流へ運ぶ食料を隠したと認めた。',[O('declare',"食料を外底から分け、内室の水葬を終えてから輸送許可を申請する",'application',[give('outerBase','coffin','shore'),give('food','outerBase','yoru'),give('coffin','shore','party'),move('party family bearers','shore','river'),give('coffin','party','river'),set('funeral'),move('party family bearers','river','shore'),move('party yoru','shore','office'),set('declared')]),O('quiet',"遺族に事情を伝えて棺を待棺所へ戻し、受取人を呼びに行く",'postponed',[give('coffin','shore','party'),move('party family bearers','shore','mortuary'),give('coffin','party','mortuary'),set('postponed'),move('party','mortuary','shore','threshold','jetty'),move('party recipient','jetty','threshold','shore')])]);
 s.node('application','office',['yoru','inspector'],'検査官は今回の包みの量と行先を記録した。恒久的な免税ではなく、この便の臨時許可を審査する。受取人にも照会を取りに行く必要がある。',[O('permit',"受取人を窓口へ案内し、今回限りの確認と許可を得てから食料を運ぶ",'@informed',[move('party','office','shore','threshold','jetty'),move('party recipient','jetty','threshold','shore','office'),set('permit'),move('party recipient yoru','office','shore','threshold','jetty'),give('food','yoru','recipient'),set('delivered')])]);
 s.node('postponed','shore',['yoru','recipient'],'受取人を桟橋から連れてきた。遺族は待棺所で待っている。食料はまだ外底に収まり、遺体とは接していない。食料を外せば棺は軽くなるが、葬儀を再開する時刻はまだ決めていない。',[O('deliver',"受取人と待棺所へ行き、食料だけを受け渡す",'@compromise',[move('party recipient yoru','shore','mortuary'),give('food','outerBase','recipient'),move('party recipient yoru','mortuary','shore','threshold','jetty'),set('delivered')])]);
 s.end('informed',"水葬と許可された食料輸送","遺族の了承を得て、遺体を納めた内室は本来の水葬経路へ送り出した。食料は外底から分け、受取人の照会を経た今回限りの輸送許可で下流集落へ届けた。恒久的な通行税と輸送制度の見直しは申請として残る。",and(s.is('funeral'),s.is('permit'),s.is('delivered'),s.is('bodyAt','coffin'),s.is('foodAt','recipient')));
 s.end('contract',"重い棺を下流へ曳く","棺を浅瀬の段差の先へ曳いた。下流の受取人は葬送桟橋で外底だけを外して食料を受け取り、遺体を封じた内室を水葬経路へ戻した。荷の由来と輸送資格を調べないまま、棺に食料を隠す方法は残った。",and(s.is('funeral'),s.is('delivered'),not(s.is('inspected')),s.is('coffinAt','river')));
 s.end('compromise',"水葬を延期して食料を届ける","遺族の了承を得て、棺と遺体は待棺所へ戻した。食料だけを外底から取り出して下流の受取人へ届けた。飢えへの手当てはできたが、水葬は未完了で、食料の輸送許可も得ていない。",and(s.is('postponed'),s.is('coffinAt','mortuary'),s.is('delivered'),not(s.is('funeral'))));
 rows.push(s.done());
}
{
 const s=story(9,{junction:'鼠の集まる分岐',work:'清掃区画',granary:'穀倉の外室',store:'共同倉庫'},[['junction','work'],['junction','granary'],['granary','store']]);
 s.entity('eda','junction','eda').entity('cleaners','work','cleaners',{kind:'group'}).entity('storekeeper','granary','storekeeper').entity('clerks','store','clerks',{kind:'group'}).entity('rats','granary',null,{kind:'group'}).entity('grain','granary').entity('plans','eda').entity('pillars','junction');
 for(const k of ['structureChecked','causeKnown','zones','holes','verified','hunted','received'])s.bool(k);
 s.fact('plans','旧図に残された測点と地下水位を確認した').fact('structure','旧図・支柱の測点・亀裂・地下水位を比較し、この区画には新しい変位がないと確認した').fact('cause','一斉に行った石灰清掃が餌場と巣の臭いを失わせ、鼠を穀倉へ追い出した');
 s.brief="鼠が一斉に地下から地上へ逃げました。崩落の前触れか、別の原因があるのか確かめてください。";
 s.past=["清掃組合が石灰を使った清掃を広い区画で同時に行い、鼠は餌場と巣の臭いを失った。追い出された群れは地上の穀倉へ移動したが、穀倉番が内扉を閉めており、穀物のある室内へはまだ入っていない。鼠の移動と崩落は無関係である。"];
 s.authoringNotes={"notice":"以下の事実はq009を成立させる世界設定上の制約です。これらを台詞、説明、選択肢としてシナリオへ直接反映する必要はありません。ただし、生成・改稿時に矛盾させてはいけません。","factsHeading":"世界設定上の事実","facts":["この地域では、鼠が一斉に地上へ逃げる現象は、落石、空気の流れの変化、地下水の上昇に先行することがあり、崩落警戒の根拠の一つとされています。ただし、鼠の移動だけでは崩落を確定できません。","崩落の有無は、測量士が残した旧図、支柱の測点、亀裂、地下水位を比較して判断します。本件の区画には新しい変位がありません。","石灰清掃を区画ごとに時期をずらせば、鼠を一方向へ一斉に追い出さず、罠と封鎖によって移動先を制御できます。穀倉の外室と穀物庫は内扉で分かれています。"]};
 s.revealText=s.past.join(' ');s.progression="崩落の確認、清掃時期の分散、鼠の侵入口封鎖、穀物移送を独立した状態として扱う。作業順を変えても、実施済みの作業だけを結果へ引き継ぐ。";
 s.node('entry','junction',['eda'],'エダは鼠の流れを見て「崩れる前触れか」と尋ねた。穀倉番からは、内扉を閉じて持ちこたえていると連絡が来ている。',[O('trace',"旧図、支柱、亀裂、地下水位を比較し、石灰の跡を清掃区画へ追う",'work',[see('plans','plans'),see('structure','pillars',s.known('plans')),set('structureChecked'),move('party','junction','work'),see('cause','cleaners'),set('causeKnown')]),O('hunt',"穀倉の外室で群れを追い払い、内扉を守る",'@contract',[move('party','junction','granary'),move('rats','granary','junction','work'),set('hunted')],{combat:true}),O('move',"穀倉へ行き、共同倉庫への避難搬送を手配する",'granary',[move('party','junction','granary')])]);
 s.node('work','work',['cleaners'],when(s.is('zones'),'清掃係は合意した区画表を保持している。すでに撒いた石灰は取り消せない。次回から清掃する区画と時期をずらし、鼠の移動先を罠と封鎖で制御する。','清掃係は石灰の袋を見せた。「全部きれいにするように、と」。鼠を追い出した先は穀倉だった。'),[O('zones',"清掃係と次回以降の区画と時期を分ける合意をする",'work',[set('zones')],{when:not(s.is('zones'))}),O('granary',"鼠の移動経路をたどり、穀倉の侵入口を確かめに行く",'granary',[move('party','work','junction','granary')],{once:false})]);
 s.node('granary','granary',['storekeeper'],[when(s.is('holes'),'外室への穴は塞いである。内扉は引き続き閉めている。','鼠はまだ外室にいる。穀倉番は内扉を押さえ、穀物との間を守っている。'),when(s.is('zones'),'次回からの清掃区画と時期の分散は合意済みだ。','清掃範囲の合意はまだ取っていない。')],[O('holes',"外室の鼠を別方向へ誘導してから侵入口を塞ぐ",'granary',[move('rats','granary','junction','work'),set('holes')],{when:not(s.is('holes'))}),O('work',"清掃係へ戻り、区画と時期の分け方を決める",'work',[move('party','granary','junction','work'),see('cause','cleaners'),set('causeKnown')],{once:false}),O('verify',"構造確認、清掃の合意、侵入口の封鎖を照合する",'@informed',[move('party','granary','junction'),see('plans','plans'),see('structure','pillars',s.known('plans')),set('structureChecked'),move('party','junction','work'),see('cause','cleaners'),set('causeKnown'),set('verified')],{when:and(s.is('zones'),s.is('holes')),requirement:'清掃の区画分け・侵入口の封鎖'}),O('grain',"共同倉庫の受入れを確認し、穀物を運び込む",'@compromise',[move('party','granary','store'),move('party clerks','store','granary'),give('grain','granary','party'),move('party clerks','granary','store'),give('grain','party','clerks'),set('received')])]);
 s.end('informed',"清掃範囲と鼠の入口を分ける","旧図、支柱の測点、亀裂、地下水位を比較し、この区画に新しい変位がないことを確認した。石灰清掃が鼠を追い出した経路を突き止め、次回から清掃区画と時期を分け、穀倉の侵入口を塞いだ。この区画の崩落警戒は解除したが、他区画の安全までは断定していない。",and(s.is('structureChecked'),s.is('causeKnown'),s.is('zones'),s.is('holes'),s.is('verified')));
 s.end('contract',"穀倉前の群れを追い払う","外室の群れを追い払い、内扉の向こうの穀物を守った。鼠を一斉に追い出した清掃方法は変わらず、構造物の安全も調べていない。別の出口から群れが戻る可能性が残る。",s.is('hunted'));
 s.end('compromise',"穀物を共同倉庫へ移す","受入れ係と数量を照合し、穀物を共同倉庫へ運び込んだ。共同の入出庫帳で、誰に配られたかが見えるようになった。穀物は当面守られたが、清掃方法、鼠の侵入口、崩落の有無は、実際に確認した範囲を超えて解決したことにはならない。",and(s.is('received'),s.is('grainAt','clerks')));
 rows.push(s.done());
}
{
 const s=story(10,{control:'高所の水門操作室',near:'手前の避難通路',deep:'奥の作業区画',shaft:'旧工事用の縦坑',ground:'地上の救助口',landing:'帳簿のある踊り場'},[['control','near'],['near','deep'],['control','shaft'],['shaft','ground'],['near','landing'],['control','ground']]);
 s.entity('keeper','control','gatekeeper').entity('rine','ground','rine').entity('nearPeople','near','nearpeople',{kind:'group'}).entity('deepPeople','deep','deeppeople',{kind:'group'}).entity('crew','ground','pumpcrew',{kind:'group'}).entity('book','landing').entity('rescueRope','keeper');
 for(const k of ['shaftChecked','ropeRigged','nearSaved','deepSaved','bookSaved','closed','pumpHandover','testimony','filed'])s.bool(k);
 s.fact('delay','門番は未承認工事を知りながら閉門命令を待ち、住民の避難時間を稼いでいた').fact('book','補強工事の台帳には必要な検査印と契約印が欠けている');
 s.brief="老朽水門を閉じなければ上層市街へ水が流れ込みます。しかし、水門の内側には地下住民が五人残っています。代わりの出口を探してください。";
 s.past=["水門の補強工事は契約上の検査と承認を受けておらず、安全性を確認できない。最後まで操作室に残った門番は、その事実を知りながら閉門命令を待ち、内側の住民が逃げる時間を稼いでいる。手前の区画に三人、奥の区画に二人がいる。旧工事用の縦坑は地上へ通じるが、長く封鎖されており、上下両端を検査するまで避難には使えない。"];
 s.authoringNotes={"notice":"以下の事実はq010を成立させる世界設定上の制約です。これらを台詞、説明、選択肢としてシナリオへ直接反映する必要はありません。ただし、生成・改稿時に矛盾させてはいけません。","factsHeading":"世界設定上の事実","facts":["水門は下層排水区と上層市街を隔てる非常用の門です。閉じれば上層への流入を止められますが、老朽化した機構は閉門後に固着するため、大規模な工事を行うまで再び開けられません。","門番は安全側の操作室から水門を閉じた後、地上へ続く操作梯子で脱出できます。住民五人は水門の内側にいるため、閉門時に残っていれば通常経路では救助できません。","旧工事用の縦坑は内側の二つの区画と地上を結びます。封鎖を解き、地上側と地下側の足場、換気、縄の固定点を検査した後に限り、避難路として使えます。","灯番組合は下層通路の照明、避難経路図、地上での帰還確認を担当しています。リネは水門の管理者ではありませんが、門番からの非常連絡を受け、地上側の救助名簿と排水隊の招集を引き受けています。","補強工事の帳簿には必要な検査印と契約印がありません。門番は未承認工事と閉門を遅らせた理由を証言できます。帳簿だけ、または証言だけでは、工事と判断の全体を確定できません。"]};
 s.revealText=s.past.join(' ');s.progression="縦坑の安全確認、住民三人と二人の地上到着、帳簿の回収、門番の証言を別々に記録する。閉門前には内側に残る人数を表示し、固着後に救助した扱いにはしない。";
 s.node('entry','control',['keeper'],'門番は安全側の操作室で閉門綱を握っている。「手前に三人、奥に二人。閉めたら固着する。工事なしでは開け直せん」。門番用の操作梯子は地上へ続く。住民を逃がす旧工事用の縦坑には封鎖札があり、足場も換気も未確認だった。',[O('shaft',"縦坑の封鎖を解き、上下両端を検査してリネへ連絡する",'operations',[move('party','control','shaft','ground'),move('party','ground','shaft','control'),set('shaftChecked'),see('delay','keeper')]),O('close',"五人が残ることを確認し、住民救助を断念して閉門する",'@contract',[set('closed'),move('party keeper','control','ground')],{requirement:'住民五人が内側に残る。閉門後は戻れない'}),O('pump',"縦坑を検査してリネへ連絡し、到着した排水隊へ現場を引き継ぐ",'@compromise',[move('party','control','shaft','ground'),set('shaftChecked'),move('party crew','ground','shaft','control'),set('pumpHandover'),move('party keeper','control','ground')])]);
 const finish=[set('closed'),move('party keeper','control','ground')];
 s.node('operations','control',['keeper'],['縦坑の封鎖を解き、上下両端の足場、換気、縄の固定点を確認した。リネは地上で到着人数を記録する。作業の順番は選べる。救助縄は奥の渡りに固定し、撤収まで残す。',when(s.is('nearSaved'),'手前の三人は地上に到着済み。','手前の三人はまだ通路にいる。'),when(s.is('deepSaved'),'奥の二人は地上に到着済み。','奥の二人はまだ作業区画にいる。'),when(s.is('bookSaved'),'帳簿は地上のリネが預かっている。','帳簿は踊り場に残っている。')],[O('near',"手前の三人を縦坑から地上へ送り、リネに到着を確認する",'operations',[move('party','control','near'),move('party nearPeople','near','control','shaft','ground'),set('nearSaved'),move('party','ground','shaft','control')],{when:not(s.is('nearSaved'))}),O('deep',"救助縄を張り、奥の二人を地上へ送って到着を確認する",'operations',[give('rescueRope','keeper','party'),move('party','control','near'),give('rescueRope','party','near'),set('ropeRigged'),move('party','near','deep'),move('party deepPeople','deep','near','control','shaft','ground'),set('deepSaved'),move('party','ground','shaft','control')],{when:not(s.is('deepSaved'))}),O('book',"踊り場の帳簿を回収し、地上のリネへ預ける",'operations',[move('party','control','near','landing'),give('book','landing','party'),see('book','book'),move('party','landing','near','control','shaft','ground'),give('book','party','rine'),set('bookSaved'),move('party','ground','shaft','control')],{when:not(s.is('bookSaved'))}),O('all',"五人の到着を照合し、縄を回収して門番に閉門してもらう",'ground',[move('party','control','near'),give('rescueRope','near','party'),move('party','near','control'),set('ropeRigged',false),...finish],{when:and(s.is('nearSaved'),s.is('deepSaved')),requirement:'手前三人・奥二人の地上到着'}),O('partial',"救助できた組だけを確定し、残る組を断念して閉門する",'@partial',finish,{when:or(and(s.is('nearSaved'),not(s.is('deepSaved'))),and(s.is('deepSaved'),not(s.is('nearSaved')))),requirement:'表示中の未救助者が内側に残る。閉門後は戻れない'}),O('close',"まだ五人が残る状態で閉門する",'@contract',finish,{when:and(not(s.is('nearSaved')),not(s.is('deepSaved'))),requirement:'住民五人が内側に残る'}),O('pump',"現在の救助数と証拠の所在を伝え、到着した排水隊へ引き継ぐ",'@compromise',[move('party','control','shaft','ground'),move('party crew','ground','shaft','control'),set('pumpHandover'),move('party keeper','control','ground')])]);
 s.node('ground','ground',['keeper','rine','nearPeople','deepPeople'],'リネの名簿で住民五人の到着を照合した。門番は閉門後、操作梯子から地上へ出た。ここからは救助の成否ではなく、何を記録に残すかを選ぶ。',[O('testimony',"帳簿と門番本人の証言をリネの報告に載せる",'@informed',[set('testimony'),set('filed')],{when:s.is('bookSaved'),requirement:'帳簿がリネの手元にある'}),O('rescue',"全員の救助報告だけで区切る",'@rescued')]);
 const all=and(s.is('nearSaved'),s.is('deepSaved'),s.is('nearPeopleAt','ground'),s.is('deepPeopleAt','ground'),s.is('keeperAt','ground'),s.is('closed'));
 s.end('informed',"全員を救い、工事の記録と証言を残す","住民五人と門番が地上へ帰った。検査印と契約印を欠く帳簿と門番本人の証言がリネの報告に載り、未承認の補強工事と閉門の遅れを調べる根拠になった。責任の裁定は救助の後に残された。",and(all,s.is('bookAt','rine'),s.is('testimony'),s.is('filed')));
 s.end('rescued',"全員の救助を完了する","住民五人を縦坑から地上へ送り、到着を確認した。門番は水門を閉じて操作梯子から脱出した。救助の成功は報告された。回収済みの帳簿があればリネの手元に残るが、帳簿と門番の証言をそろえた調査報告は作っていない。",all);
 s.end('partial',"救助済みの組を確定して閉門","地上への到着を確認できた組だけを救助名簿へ記した。門番は水門を閉じて脱出した。閉門時に内側へ残った組は固着した水門の向こうに取り残され、生死を確認できていない。",and(s.is('closed'),or(and(s.is('nearSaved'),not(s.is('deepSaved'))),and(s.is('deepSaved'),not(s.is('nearSaved'))))));
 s.end('contract',"住民を救う前に閉門","住民五人が内側に残ると確認した上で、門番は水門を閉じて地上へ出た。上層市街への流入は止まったが、固着した水門の向こうに残る五人の帰還は確認されていない。",and(s.is('closed'),not(s.is('nearSaved')),not(s.is('deepSaved'))));
 s.end('compromise',"到着した排水隊へ引き継ぐ","リネが招集した排水隊が操作室へ到着し、現在の救助数、残留者の位置、縦坑の状態、帳簿の所在を引き継いだ。門番は地上へ出た。救助済みの住民は地上に残り、未救助者の帰還を先取りして報告しなかった。",and(s.is('pumpHandover'),s.is('crewAt','control'),s.is('keeperAt','ground'),not(s.is('closed'))));
 s.invariant('near_arrival',{op:'eq',left:s.v('nearSaved'),right:s.is('nearPeopleAt','ground')},'到着人数は実際の所在と一致する');
 s.invariant('deep_arrival',{op:'eq',left:s.v('deepSaved'),right:s.is('deepPeopleAt','ground')},'到着人数は実際の所在と一致する');
 rows.push(s.done());
}
export default rows;
